import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'
import { compileScript, parse } from '@vue/compiler-sfc'

const canvas = fs.readFileSync(new URL('./UiDesignerCanvas.vue', import.meta.url), 'utf8')
const fabricCanvas = fs.readFileSync(new URL('./UiDesignerFabricCanvas.vue', import.meta.url), 'utf8')
const fabricFactory = fs.readFileSync(new URL('../fabric/fabricNodeFactory.ts', import.meta.url), 'utf8')
const propertyField = fs.readFileSync(new URL('./UiPropertyField.vue', import.meta.url), 'utf8')
const nodePanel = fs.readFileSync(new URL('./UiDesignerNodePanel.vue', import.meta.url), 'utf8')
const shell = fs.readFileSync(new URL('./UiDesignerShell.vue', import.meta.url), 'utf8')
const toolbar = fs.readFileSync(new URL('./UiDesignerToolbar.vue', import.meta.url), 'utf8')
const sceneTabs = fs.readFileSync(new URL('./UiDesignerSceneTabs.vue', import.meta.url), 'utf8')
const hostLifecycle = fs.readFileSync(new URL('../composables/useUiDesignerRendererHost.ts', import.meta.url), 'utf8')
const designerController = fs.readFileSync(new URL('../composables/useUiDesigner.ts', import.meta.url), 'utf8')
const routedView = fs.readFileSync(new URL('../../../views/UiDesignerView.vue', import.meta.url), 'utf8')

const compileComponent = (name: string) => {
  const source = fs.readFileSync(new URL(name, import.meta.url), 'utf8')
  const parsed = parse(source, { filename: name })
  assert.deepEqual(parsed.errors, [])
  assert.doesNotThrow(() => compileScript(parsed.descriptor, { id: `canvas-authoring-${name}`, inlineTemplate: true }))
}

test('authoring canvas compiles with Fabric as the single design renderer', () => {
  for (const name of ['./UiDesignerCanvas.vue', './UiDesignerFabricCanvas.vue', './UiPropertyField.vue']) compileComponent(name)
  assert.equal(fs.existsSync(new URL('./UiCanvasNode.vue', import.meta.url)), false)
  assert.equal(fs.existsSync(new URL('./UiDesignerStaticNodePreview.vue', import.meta.url)), false)
})

test('UI designer keeps the isolated runtime only for explicit preview', () => {
  assert.match(canvas, /useUiDesignerRendererHost/)
  assert.match(canvas, /active: \(\) => rendererRequested\.value/)
  assert.match(canvas, /<UiDesignerFabricCanvas/)
  assert.match(canvas, /v-show="!previewing"/)
  assert.match(canvas, /data-ui-id="ui-designer-runtime-canvas-frame"/)
  assert.match(canvas, /v-show="previewing"/)
  assert.doesNotMatch(canvas, /UiCanvasNode|node-layer/)
  assert.match(canvas, /preview-interactive/)
  assert.match(canvas, /@error="rendererHost\.onIframeError"/)
  assert.match(canvas, /rendererFailureCode/)
  assert.match(canvas, /rendererHost\.retry\(\)/)
  assert.match(canvas, /rendererDisconnected/)
  assert.match(canvas, /data-ui-id="ui-designer-runtime-canvas-restart"/)
  assert.doesNotMatch(canvas, /rendererHost\.sendInput/)
  assert.match(fabricCanvas, /new Canvas\(element/)
  assert.match(fabricCanvas, /data-ui-id="ui-designer-fabric-canvas"/)
})

test('editor and in-game preview reuse the canonical iframe with distinct execution behavior', () => {
  assert.match(toolbar, /const fullscreenPreview = computed\(\(\) => designer\.isEditorPreviewing \|\| designer\.isPreviewing\)/)
  assert.match(toolbar, /data-ui-id="ui-designer-preview-exit"/)
  assert.match(toolbar, /ui-designer-game-preview-enter/)
  assert.match(toolbar, /canStartEditorPreview/)
  assert.match(toolbar, /:disabled="!designer\.canStartPreview"/)
  assert.match(toolbar, /gamePreview/)
  assert.match(shell, /UiDesignerInspector[^>]*v-show="!fullscreenPreview"/)
  assert.match(shell, /UiDesignerSceneTabs[^>]*v-show="!fullscreenPreview"/)
  assert.match(canvas, /v-if="!previewing" class="canvas-toolbar"/)
  assert.match(canvas, /v-if="!previewing && document\.canvas\.rulers"/)
  assert.match(canvas, /const gamePreviewing = computed/)
  assert.match(canvas, /previewInteractive = computed\(\(\) => previewing\.value[\s\S]*executionMode\.value !== 'authoring'/)
  assert.match(canvas, /pointer-events: none/)
  assert.match(canvas, /touch-action: none/)
})

test('design and code keep one mounted Fabric canvas while the runtime starts lazily for preview', () => {
  assert.match(shell, /<template v-else>[\s\S]*UiDesignerCanvas[^>]*v-show="designer\.editingMode === 'design' \|\| fullscreenPreview"[\s\S]*UiDesignerCodePanel[^>]*v-show="designer\.editingMode === 'code' && !fullscreenPreview"/)
  assert.doesNotMatch(shell, /UiDesignerCanvas v-else-if/)
  assert.doesNotMatch(canvas, /ui-designer-canvas-refresh|rendererHost\.refreshCanvas/)
  assert.match(canvas, /const rendererRequested = computed\(\(\) => previewing\.value \|\| unwrap\(designer\.previewStatus\) === 'preparing'\)/)
  assert.match(hostLifecycle, /active\?: \(\) => boolean/)
  assert.match(hostLifecycle, /if \(rendererRequested\(\)\) void start\(\)/)
  assert.match(hostLifecycle, /const activeStop = watch\(rendererRequested/)
  assert.match(hostLifecycle, /else if \(session \|\| disposingSession \|\| retainedStaleSessions\.size\) \{\s*void dispose\('shutdown'\)/)
  const sceneWatcher = hostLifecycle.slice(hostLifecycle.indexOf('const sceneStop = watch('), hostLifecycle.indexOf('const draftStop = watch('))
  assert.match(sceneWatcher, /if \(rendererRequested\(\)\) syncScene\(sceneChanged\)/)
  assert.match(hostLifecycle, /if \(pendingMountRevision !== null\) \{\s*queueSceneSync\(forceMount\)/)
  assert.match(hostLifecycle, /const previewNeedsLatestMount = sceneSyncQueued && options\.executionMode\(\) !== 'authoring'/)
  assert.match(hostLifecycle, /syncScene\(previewNeedsLatestMount\)/)
  assert.match(hostLifecycle, /if \(!previewNeedsLatestMount\) options\.onExecutionModeReady/)
  const selectionSync = hostLifecycle.slice(hostLifecycle.indexOf('const syncSelection ='), hostLifecycle.indexOf('const stopBackend ='))
  assert.match(selectionSync, /options\.executionMode\(\) !== 'full-preview'/)
  const modeWatcher = hostLifecycle.slice(hostLifecycle.indexOf('const executionModeStop = watch('), hostLifecycle.indexOf('onMounted(() =>'))
  assert.match(modeWatcher, /syncScene\(true\)/)
  assert.match(modeWatcher, /status\.value === 'error' && !session && !disposingSession[\s\S]*void retry\(\)/)
  const previewStart = designerController.slice(designerController.indexOf('const startPreview ='), designerController.indexOf('const stopPreview ='))
  assert.ok(previewStart.indexOf('flushDrafts') < previewStart.indexOf("previewExecutionMode.value = 'full-preview'"))
  assert.doesNotMatch(previewStart, /isPreviewing\.value = true/)
  const editorPreviewStart = designerController.slice(designerController.indexOf('const startEditorPreview ='), designerController.indexOf('const stopEditorPreview ='))
  assert.ok(editorPreviewStart.indexOf('flushDrafts') < editorPreviewStart.indexOf("previewExecutionMode.value = 'editor-preview'"))
  assert.doesNotMatch(editorPreviewStart, /isEditorPreviewing\.value = true/)
  const previewReady = designerController.slice(designerController.indexOf('const acknowledgePreviewExecutionMode ='), designerController.indexOf('const failPreview ='))
  assert.ok(previewReady.indexOf("setEditingMode('design')") < previewReady.indexOf("isPreviewing.value = mode === 'full-preview'"))
})

test('resource refresh follows an in-flight edit with the latest complete scene', () => {
  assert.match(hostLifecycle, /const sceneRevisionAtStart = revision[\s\S]*if \(revision !== sceneRevisionAtStart\) queueSceneSync\(true\)[\s\S]*postPendingResourceRefresh\(\)/)
})

test('renderer status appears only inside preview and never blocks Fabric authoring', () => {
  assert.doesNotMatch(canvas, /runtime-disabled/)
  assert.match(canvas, /<template v-if="previewing">[\s\S]*canvasSyncing[\s\S]*canvas-runtime-state/)
  assert.match(canvas, /\.canvas-runtime-state \{[^}]*top: 8px;[^}]*right: 8px;[^}]*pointer-events: none;/)
  assert.match(canvas, /\.canvas-runtime-state \.el-button \{ pointer-events: auto; \}/)
})

test('renderer host does not settle a mounted receipt from the wrong execution mode', () => {
  const messageHandlerStart = hostLifecycle.indexOf('const onMessage =')
  const mountedHandler = hostLifecycle.slice(hostLifecycle.indexOf("if (message.kind === 'mounted'", messageHandlerStart), hostLifecycle.indexOf("if (message.kind === 'scene-state'", messageHandlerStart))
  assert.match(mountedHandler, /message\.payload\.executionMode === options\.executionMode\(\)/)
  assert.match(mountedHandler, /if \(!mountedModeMatches\)/)
  assert.match(mountedHandler, /pendingMountRevision = null/)
  assert.match(mountedHandler, /status\.value = 'loading'/)
  assert.match(mountedHandler, /syncScene\(true\)/)
})

test('pre-mount host scene-state does not become a protocol fatal after mount is queued', () => {
  const messageHandler = hostLifecycle.slice(hostLifecycle.indexOf('const onMessage ='), hostLifecycle.indexOf('const onIframeLoad ='))
  assert.match(messageHandler, /const sceneStateHasDocumentIdentity = sceneStatePayload\?\.mountedDocumentSceneId !== null/)
  assert.match(messageHandler, /candidateEnvelope\?\.kind === 'scene-state' && sceneStateHasDocumentIdentity/)
  assert.match(messageHandler, /candidateEnvelope\?\.kind === 'mounted' && \(pendingMountRevision !== null \|\| mountedDocumentSceneId\.value !== null\)/)
  assert.match(messageHandler, /sceneStateHasDocumentIdentity[\s\S]*minimumRevision: revision/)
})

test('renderer restart stops any retained owner before starting a replacement session', () => {
  const retryBlock = hostLifecycle.slice(hostLifecycle.indexOf('const retry ='), hostLifecycle.indexOf('function installMessageListener'))
  assert.match(retryBlock, /session \|\| disposingSession \|\| retainedStaleSessions\.size/)
  assert.match(retryBlock, /await dispose\('shutdown', 'shutdown', true\)/)
  assert.ok(retryBlock.indexOf("await dispose('shutdown'") < retryBlock.indexOf('await start()'))
})

test('authoring content uses Fabric objects while the iframe remains preview-only', () => {
  assert.match(canvas, /data-ui-id="ui-designer-runtime-canvas-frame"/)
  assert.match(fabricFactory, /FabricImage|Textbox|createParticle|createProgress|createVideo/)
  assert.doesNotMatch(canvas, /authoring-frame|UiCanvasNode|resourcePreviewUrls/)
})

test('container focus retains the scope boundary and exposes a visible way back', () => {
  assert.match(fabricFactory, /collectNodeSubtreeIds\(document, \[scopeNodeId\]\)/)
  assert.match(fabricFactory, /if \(scopeNodeId === 'node_root'\) scopedIds\.delete\(scopeNodeId\)/)
  assert.match(fabricFactory, /if \(left\.id === scopeNodeId\) return -1/)
  assert.match(canvas, /designer\.selectNodes\(node\.children\.length \? \[node\.children\[0\]\] : \[node\.id\]\)/)
  assert.match(canvas, /const exitContainer = \(\) => \{[\s\S]*editStack\.value = editStack\.value\.slice\(0, -1\)[\s\S]*designer\.selectNodes\(\[editingRootId\.value\]\)/)
  assert.match(canvas, /data-ui-id="ui-designer-container-scope"[\s\S]*data-ui-id="ui-designer-container-scope-exit"[\s\S]*@click="exitContainer"/)
  assert.match(canvas, /\.canvas-edit-breadcrumb \{[^}]*top: 8px;[^}]*left: 8px;/)
  assert.match(fabricCanvas, /props\.designer\.selectNodes\(ids\.length \? ids : \[props\.scopeNodeId\]\)/)
  assert.match(nodePanel, /const parentId = primary\?\.type === 'container' \? primary\.id : primary\?\.parentId \?\? 'node_root'/)
  assert.match(canvas, /designer\.addNode\(nodeType, editingRootId\.value, worldFromClient\(event\)\)/)
})

test('canvas interactions reject native selection and image dragging without blocking inline text editing', () => {
  assert.match(canvas, /@pointerdown\.capture="handleViewportPointerDown"/)
  assert.match(canvas, /@selectstart="preventNativeCanvasSelection"/)
  assert.match(canvas, /@dragstart="preventNativeCanvasDrag"/)
  assert.match(canvas, /window\.getSelection\(\)\?\.removeAllRanges\(\)/)
  assert.match(canvas, /\.canvas-viewport \{[^}]*user-select: none;[^}]*-webkit-user-select: none;[^}]*-webkit-user-drag: none;/)
  assert.match(fabricCanvas, /\.fabric-editor-canvas \{[^}]*user-select: none;[^}]*-webkit-user-select: none;[^}]*-webkit-user-drag: none;/)
  assert.match(fabricCanvas, /\.fabric-editor-canvas :deep\(textarea\) \{ user-select: text;/)
})

test('canvas pans only with Space plus left drag or middle drag and resizes freely unless Shift is held', () => {
  assert.match(canvas, /const spaceDrag = event\.button === 0 && spacePressed\.value/)
  assert.match(canvas, /if \(event\.button !== 1 && !spaceDrag\) return/)
  assert.match(fabricCanvas, /uniformScaling: false/)
  assert.match(fabricCanvas, /uniScaleKey: 'shiftKey'/)
  assert.match(fabricCanvas, /centeredKey: 'altKey'/)
  assert.match(fabricCanvas, /\(event\.e as MouseEvent\)\.shiftKey/)
  assert.match(fabricCanvas, /preserveAspect: shiftKey, fromCenter: altKey/)
  assert.match(fabricCanvas, /accumulateRotationDegrees\([\s\S]*state\.lastFabricRotation = wrappedAngle[\s\S]*state\.accumulatedRotation = accumulatedAngle/)
  assert.match(fabricCanvas, /canvas\.getScenePoint\(event\.e\)/)
  assert.match(fabricCanvas, /pointerResizeDelta\(node, state\.originRect, handle, pointer, altKey\)/)
  assert.match(fabricCanvas, /const drafts = unwrap\(props\.designer\.draftRects\)/)
  assert.match(fabricCanvas, /const positions = unwrap\(props\.designer\.draftPositions\)/)
  assert.match(fabricCanvas, /object\.setPositionByOrigin\(new Point\(draftPosition\.x, draftPosition\.y\)/)
  assert.match(fabricFactory, /centeredRotation: true/)
  assert.doesNotMatch(fabricFactory, /transformAnchorPoint/)
  assert.match(designerController, /previewNodeRotation = \(nodeId: string, rotation: number\)/)
  assert.match(designerController, /const commitDraftRotation = \(nodeId: string\)[\s\S]*node\.props\.rotate = normalizeGeometryInteger\(pendingRotation, node\.props\.rotate\)[\s\S]*'Rotate node'/)
})

test('sprite resource selection carries intrinsic dimensions into one controller transaction', () => {
  assert.match(designerController, /const setSpriteResource =/)
  assert.match(designerController, /const width = normalizeGeometryInteger\(dimensions\.width/)
  assert.match(designerController, /node\.props\.height = height/)
  assert.match(designerController, /const constrainsChildren = parent\?\.type === 'container' && parent\.props\.clip/)
  assert.match(designerController, /const fitScale = constrainsChildren \? Math\.min\(1, parentRect\.width \/ width, parentRect\.height \/ height\) : 1/)
  assert.match(designerController, /node\.props\.anchorX = 0\.5/)
  assert.match(designerController, /node\.props\.anchorY = 0\.5/)
  assert.match(designerController, /replaceActiveDocument\(next, 'Select sprite image'/)
})

test('nested nodes do not light every ancestor and parent bounds constrain transforms', () => {
  assert.match(fabricFactory, /const nodeAncestors =/)
  assert.match(fabricFactory, /ancestors\.some\(\(ancestor\) => ancestor\.locked\)/)
  assert.match(fabricFactory, /ancestors\.every\(\(ancestor\) => ancestor\.props\.visible\)/)
  assert.match(fabricFactory, /absolutePositioned: true/)
  assert.match(fabricFactory, /ancestor\.type === 'container' && ancestor\.props\.clip/)
  assert.match(fabricFactory, /const clipBoundary = \(width: number, height: number\) => boundary\(width, height, \{ fill: '#000000' \}\)/)
  assert.match(fabricFactory, /cropX,[\s\S]*cropY,[\s\S]*new Group\(\[boundary\(node\.props\.width, node\.props\.height\), image\]/)
  assert.doesNotMatch(fabricFactory, /group\.clipPath = clip/)
  assert.match(fabricFactory, /const clip = clipBoundary\(container\.props\.width, container\.props\.height\)/)
  assert.match(designerController, /clampNodePositionToParent/)
  assert.match(designerController, /clampNodeRectToParent/)
  assert.match(designerController, /collectNodeSubtreeIds/)
})

test('bounded number sliders keep both end thumbs inside the inspector column', () => {
  assert.match(propertyField, /\.number-control :deep\(\.el-slider\)[^{]*\{[^}]*box-sizing: border-box;[^}]*padding-inline: 10px;/)
})

test('rapid project generations serialize disposal before the newest host start', () => {
  assert.match(hostLifecycle, /if \(disposePromise\) \{\s*if \(!coordinatePendingStarts \|\| disposeCoordinatesPendingStarts\) return disposePromise/)
  const disposeIndex = hostLifecycle.indexOf("await dispose('project-change', 'project-change', false)")
  const startIndex = hostLifecycle.indexOf('rendererAdapter.start(generation)')
  assert.ok(disposeIndex >= 0 && startIndex > disposeIndex)
  assert.match(hostLifecycle, /epoch !== startEpoch/)
  assert.match(hostLifecycle, /cancelMountedWatchdog = scheduleUiDesignerRendererHandshakeTimeout/)
  assert.match(hostLifecycle, /messageKind === 'receipt'/)
  assert.match(hostLifecycle, /messageKind === 'fatal'/)
  assert.doesNotMatch(hostLifecycle, /UI_RENDERER_CLIENT_FAILURE/)
  assert.match(hostLifecycle, /const fail = \(acceptedFailure: UiDesignerRendererFailure\)/)
  assert.match(hostLifecycle, /if \(failurePromise\) return failurePromise/)
  assert.match(hostLifecycle, /terminalGate\.accept\(message\)/)
  assert.doesNotMatch(hostLifecycle, /payload\.status === 'error'\) void fail/)
  assert.doesNotMatch(hostLifecycle, /error\.value = reason instanceof Error \? reason\.message/)
  assert.match(canvas, /rendererDisconnected/)
  assert.doesNotMatch(canvas, /rendererStage} \(\$\{rendererStageStatus/)
})

test('scene synchronization assigns fixed codes to export plan post snapshot and selection failures', () => {
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.sceneExport, stage\.value/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.updatePlan, stage\.value/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.mountPost, 'mount'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.patchPost, stage\.value/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.sceneSnapshot, stage\.value/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.selectionPost, stage\.value/)
  assert.doesNotMatch(hostLifecycle, /void fail\(reason\)|await fail\(reason\)/)
})

test('both ten second renderer watchdogs report distinct fixed codes and stages', () => {
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.handshakeTimeout, stage\.value/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.mountedTimeout, 'mounted'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.handshakeWatchdog, 'iframe-load'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.mountedWatchdog, 'mounted'/)
})

test('authenticated pre-mount progress renews the handshake watchdog without extending mounted waits', () => {
  assert.match(hostLifecycle, /const armHandshakeWatchdog = \(activeSessionId: string\): boolean =>/)
  assert.match(hostLifecycle, /session\?\.sessionId === activeSessionId && pendingMountRevision === null && !executionModeReady\.value/)
  assert.match(hostLifecycle, /const advancesHandshake = messageKind === 'receipt'[\s\S]*messageKind === 'hello'[\s\S]*messageKind === 'ready'[\s\S]*messageKind === 'scene-state' && !sceneStateHasDocumentIdentity/)
  assert.match(hostLifecycle, /if \(advancesHandshake && pendingMountRevision === null && !executionModeReady\.value && !armHandshakeWatchdog\(active\.sessionId\)\) return/)
  assert.match(hostLifecycle, /pendingMountRevision = revision[\s\S]*cancelHandshake\(\)/)
})

test('start confirm and iframe terminals enter the shared latch with fixed safe codes', () => {
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.startAdapter, 'start'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.startResult, 'start'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.confirmIpc, 'confirm'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.confirmIdentity, 'confirm'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.iframeLoad, 'iframe-load'/)
  assert.match(hostLifecycle, /if \(terminalFailure\) void fail\(terminalFailure\)/)
  assert.match(hostLifecycle, /void fail\(resolveUiDesignerRendererFailure\('UI_RENDERER_BRIDGE_PROTOCOL', stage\.value\)\)/)
  const startAndConfirm = hostLifecycle.slice(hostLifecycle.indexOf('const start = async'), hostLifecycle.indexOf('const messageOriginMatches'))
  assert.doesNotMatch(startAndConfirm, /result\.message/)
  assert.match(canvas, /:data-failure-code="rendererFailureCode \|\| undefined"/)
  assert.match(canvas, /:data-failure-stage="rendererStage"/)
  assert.match(canvas, /t\('rendererDisconnected'\)/)
})

test('canvas exposes bounded renderer lifecycle diagnostics to the hidden desktop bridge', () => {
  assert.match(canvas, /data-ui-id="ui-designer-canvas"/)
  assert.match(canvas, /:data-renderer-status="rendererStatus"/)
  assert.match(canvas, /:data-renderer-stage="rendererStage"/)
  assert.match(canvas, /:data-renderer-failure-code="rendererFailureCode \|\| undefined"/)
  assert.match(canvas, /:data-preview-status="unwrap\(designer\.previewStatus\)"/)
  assert.match(canvas, /:data-preview-mode="requestedExecutionMode"/)
  assert.match(canvas, /:data-renderer-execution-mode="rendererHost\.executionMode\.value"/)
  assert.match(canvas, /:data-renderer-mode-ready="rendererHost\.executionModeReady\.value \? 'true' : 'false'"/)
})

test('stale renderer starts keep an opaque owner for a retryable stop', () => {
  assert.match(hostLifecycle, /retainedStaleSessions/)
  assert.match(hostLifecycle, /const stopStaleSession = async/)
  assert.match(hostLifecycle, /await stopStaleSession\(result\.value, rendererAdapter\)/)
  assert.match(hostLifecycle, /retainedStopPromise/)
  assert.match(hostLifecycle, /if \(!stopped && \(!session \|\| session\.sessionId === result\.value\.sessionId\)\)/)
  assert.match(hostLifecycle, /onExecutionModeError\?\.\(error\.value, true\)/)
  assert.doesNotMatch(hostLifecycle, /if \(.*stale.*\)\s*session = result\.value/)
  assert.match(hostLifecycle, /previous isolated UI canvas session was kept/)
})

test('renderer scene sync waits for the iframe handshake and mounted revision', () => {
  assert.match(hostLifecycle, /!engineReady \|\| !processConfirmed \|\| !iframeLoaded/)
  const pendingMountGate = hostLifecycle.indexOf('if (pendingMountRevision !== null) {')
  const nextRevision = hostLifecycle.indexOf('revision = update.revision', pendingMountGate)
  assert.ok(pendingMountGate >= 0 && nextRevision > pendingMountGate)
  assert.match(hostLifecycle, /post\('mount',[\s\S]*pendingMountRevision = revision/)
  assert.match(hostLifecycle, /message\.kind === 'mounted'[\s\S]*pendingMountRevision = null[\s\S]*syncScene\(previewNeedsLatestMount\)/)
  assert.match(hostLifecycle, /!executionModeReady\.value/)
  assert.match(hostLifecycle, /update\.kind === 'patch' && !executionModeReady\.value/)
  assert.match(hostLifecycle, /iframeLoaded = true[\s\S]*maybeRun\(\)/)
  assert.match(hostLifecycle, /options\.designer\.runtimeDiagnostics = \[\]/)
})

test('preview keeps scene tabs and controller activation locked to the captured scene', () => {
  assert.match(sceneTabs, /if \(designer\.isPreviewing\) return/)
  assert.match(designerController, /const activateScene = \(sceneId: string\) => \{\s*if \(previewOccupied\.value\) return false/)
  const contextBarrier = designerController.indexOf('const previewWasOccupied = previewOccupied.value')
  const contextDiscardPrompt = designerController.indexOf('options.confirmDiscard()', contextBarrier)
  assert.ok(contextBarrier >= 0 && contextDiscardPrompt > contextBarrier)
})

test('route teardown waits for the renderer owner before leaving the designer', () => {
  assert.match(routedView, /disposePreview\('unload'\)/)
  assert.match(routedView, /if \(shellRef\.value && !\(await shellRef\.value\.disposePreview\('unload'\)\)\) return false/)
  assert.match(shell, /if \(rawDesigner\.isPreviewing\.value\) rawDesigner\.stopPreview\(\)/)
  assert.match(shell, /disposePreview\('unload'\)\.then\(\(\) => restorePreviewState\(\)\)/)
})

test('scene-state fatal keeps the route barrier on one active owner and retries backend cleanup', () => {
  assert.match(hostLifecycle, /if \(session \|\| disposingSession\) actorDisposed = true/)
  assert.match(hostLifecycle, /if \(!actorTerminal && actorDisposed\) actorTerminal = true/)
  assert.match(hostLifecycle, /if \(messageKind === 'fatal'\) \{[\s\S]*terminalGate\.accept\(message\)[\s\S]*actorDisposed = true\s*pendingDispose\?\.acknowledge\(\)/)
  assert.match(hostLifecycle, /onExecutionModeError\?\.\(recoveryReason, !terminal\)/)
  assert.match(designerController, /const previewCleanupPending = ref\(false\)/)
  assert.match(designerController, /previewCleanupPending\.value \|\| previewDisposalInFlight\.value \|\| previewStatus\.value === 'preparing'/)
  assert.match(designerController, /failPreview = \(message = '', cleanupPending = false\)/)
})

test('terminal retry preserves the fixed cause through cleanup and resets only before a new owner starts', () => {
  assert.match(hostLifecycle, /const outcome = failureLatch\.accept\(candidate\)[\s\S]*if \(outcome\.accepted\) \{\s*failureCode\.value = outcome\.failure\.code\s*failureRecoveryReason\.value = outcome\.failure\.recoveryReason/)
  assert.match(hostLifecycle, /const authoritativeFailure = latchFailure\(acceptedFailure\)/)
  assert.match(hostLifecycle, /if \(terminalFailure\) latchFailure\(terminalFailure\)/)
  assert.match(hostLifecycle, /const terminal = await dispose\('shutdown', 'protocol-error', false\)/)
  const cleanupBarrier = hostLifecycle.indexOf("if (!await stopRetainedStaleSessions())")
  const gateReset = hostLifecycle.indexOf('terminalGate.reset()', cleanupBarrier)
  const rendererStart = hostLifecycle.indexOf('rendererAdapter.start(generation)', gateReset)
  assert.ok(cleanupBarrier >= 0 && gateReset > cleanupBarrier && rendererStart > gateReset)
  assert.match(hostLifecycle, /failureCode\.value = null\s*failureRecoveryReason\.value = ''/)
})

test('stop failures preserve a retryable disposer through unmount', () => {
  assert.match(hostLifecycle, /void dispose\('unload'\)\s*\.then\(\(barrierOk\) =>/)
  assert.match(hostLifecycle, /pendingStarts\.add\(pendingStart\)/)
  assert.match(hostLifecycle, /pendingStarts\.delete\(pendingStart\)/)
  assert.match(hostLifecycle, /pendingStartCleanup = true\s*await waitForPendingStarts\(\)/)
  assert.match(hostLifecycle, /if \(pendingStartCleanup\) return true/)
  assert.match(hostLifecycle, /const currentOk = await currentDispose\s*await waitForPendingStarts\(\)/)
  assert.match(hostLifecycle, /if \(disposed && coordinatePendingStarts\)/)
  assert.match(hostLifecycle, /if \(pendingStartCleanup \|\| queuedDisposePromise \|\| disposeCoordinatesPendingStarts\) return/)
  assert.match(hostLifecycle, /if \(barrierOk\) \{[\s\S]*unregisterPreviewDisposer\(\)[\s\S]*removeMessageListener\(\)/)
  assert.doesNotMatch(hostLifecycle, /\.finally\(unregisterPreviewDisposer\)/)
})

test('project and route cleanup await active and retained owners before terminal success', () => {
  const activeStop = hostLifecycle.indexOf('await stopBackend(active, backendReason, activeAdapter)')
  const retainedStop = hostLifecycle.indexOf('if (!await stopRetainedStaleSessions())', activeStop)
  const authoringReady = hostLifecycle.indexOf("options.onExecutionModeReady?.('authoring')", retainedStop)
  const terminalSuccess = hostLifecycle.indexOf('return true', authoringReady)
  assert.ok(activeStop >= 0 && retainedStop > activeStop)
  assert.ok(authoringReady > retainedStop && terminalSuccess > authoringReady)
  assert.match(hostLifecycle, /if \(!await stopRetainedStaleSessions\(\)\) \{\s*status\.value = 'error'[\s\S]*return false/)
  assert.match(hostLifecycle, /if \(!active\) \{\s*const ok = await stopRetainedStaleSessions\(\)/)
  assert.match(hostLifecycle, /stopBackend\(owner\.session, 'project-change', owner\.adapter\)/)
  assert.match(designerController, /const previewDisposalInFlight = ref\(false\)/)
  assert.match(designerController, /if \(previewDisposePromise\) return previewDisposePromise/)
  assert.match(designerController, /previewCleanupPending\.value \|\| previewDisposalInFlight\.value/)
  assert.match(shell, /previewDisposalInFlight\.value/)
  assert.match(routedView, /previewDisposalInFlight/)
})

test('preview restores the existing tree expansion state through the Element Plus tree owner', () => {
  assert.match(nodePanel, /defineExpose\(\{ getExpandedKeys, setExpandedKeys \}\)/)
  assert.match(nodePanel, /@node-expand="rememberExpanded"/)
  assert.match(nodePanel, /@node-collapse="rememberCollapsed"/)
  assert.match(nodePanel, /type === 'before' \|\| type === 'prev'/)
  assert.match(nodePanel, /type === 'after' \|\| type === 'next'/)
  assert.match(shell, /expandedNodeIds: nodePanelRef\.value\?\.getExpandedKeys\(\)/)
  assert.match(shell, /setExpandedKeys\(snapshot\.expandedNodeIds\)/)
})
