import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'
import { compileScript, parse } from '@vue/compiler-sfc'

const read = (name: string) => fs.readFileSync(new URL(name, import.meta.url), 'utf8')
const compile = (name: string) => {
  const source = read(name)
  const parsed = parse(source, { filename: name })
  assert.deepEqual(parsed.errors, [])
  assert.doesNotThrow(() => compileScript(parsed.descriptor, { id: `acceptance-${name}`, inlineTemplate: true }))
  return source
}

test('hostile main-menu acceptance controls expose stable semantic selectors', () => {
  const help = compile('./UiDesignerHelpSurface.vue')
  const welcome = compile('./UiDesignerWelcome.vue')
  const sceneTabs = compile('./UiDesignerSceneTabs.vue')
  const newScene = compile('./UiDesignerNewSceneSurface.vue')
  const nodePanel = compile('./UiDesignerNodePanel.vue')
  const toolbar = compile('./UiDesignerToolbar.vue')
  const shell = compile('./UiDesignerShell.vue')
  const canvas = compile('./UiDesignerCanvas.vue')
  const inspector = compile('./UiDesignerInspector.vue')
  const buttonStates = compile('./UiButtonStatesEditor.vue')
  const events = compile('./UiDesignerEvents.vue')
  const property = compile('./UiPropertyField.vue')
  const settings = compile('./UiDesignerSettingsSurface.vue')
  const sceneSettings = compile('./UiDesignerSceneSettingsSurface.vue')
  const openScene = compile('./UiDesignerOpenSceneSurface.vue')
  const saveAs = compile('./UiDesignerSaveAsSurface.vue')

  assert.match(help, /ui-designer-onboarding-dialog/)
  assert.match(help, /ui-designer-onboarding-skip/)
  assert.match(help, /ui-designer-onboarding-finish/)
  assert.match(welcome, /ui-designer-welcome-new-scene/)
  assert.match(welcome, /ui-designer-welcome-return/)
  assert.match(welcome, /\.welcome-panel \{[^}]*flex: 1;[^}]*width: 100%;[^}]*overflow-y: auto;/)
  assert.match(welcome, /ui-designer-recovery-restore-\$\{index\}/)
  assert.match(welcome, /ui-designer-recovery-remove-\$\{index\}/)
  assert.match(sceneTabs, /ui-designer-scene-tab-new/)
  assert.match(sceneTabs, /ui-designer-scene-tab-\$\{scene\.id\}/)
  assert.match(newScene, /ui-designer-new-scene-dialog/)
  assert.match(newScene, /ui-designer-new-scene-name/)
  assert.match(newScene, /ui-designer-new-scene-validation/)
  assert.match(newScene, /ui-designer-new-scene-confirm/)
  assert.match(newScene, /ui-designer-new-scene-cancel/)
  assert.match(nodePanel, /ui-designer-palette-\$\{type\}/)
  assert.match(canvas, /\['container', 'list', 'sprite'/)
  assert.match(toolbar, /ui-designer-preview-enter/)
  assert.match(toolbar, /ui-designer-preview-exit/)
  assert.match(toolbar, /ui-designer-home/)
  assert.match(toolbar, /ui-designer-save/)
  assert.match(toolbar, /ui-designer-save-as/)
  assert.match(toolbar, /emit\('save-as'\)/)
  assert.match(toolbar, /ui-designer-scene-settings/)
  assert.doesNotMatch(toolbar, /publishToProject|ui-designer-export/)
  assert.doesNotMatch(shell, /shortcutSaveAs/)
  assert.match(shell, /ui-designer-conflict-save-as/)
  assert.match(shell, /saveConflictAs/)
  assert.match(shell, /@home="showWelcome = true"/)
  assert.match(shell, /@editing-mode="showEditingMode"/)
  assert.match(shell, /@return-to-scene="showWelcome = false"/)
  assert.match(shell, /@scene-ready="showWelcome = false"/)
  assert.match(shell, /if \(created\) \{[\s\S]*showWelcome\.value = false/)
  assert.match(welcome, /if \(await designer\.open\([\s\S]*emit\('sceneReady'\)/)
  assert.match(welcome, /if \(await designer\.restoreRecovery\([\s\S]*emit\('sceneReady'\)/)
  assert.match(welcome, /if \(await designer\.loadTemplate\([\s\S]*emit\('sceneReady'\)/)
  assert.doesNotMatch(toolbar, /ui-designer-recovery-entry/)
  assert.doesNotMatch(shell, /surface === 'recovery'/)
  assert.doesNotMatch(shell, /UiDesignerStatusBar/)
  assert.doesNotMatch(canvas, /canvas-hint/)
  assert.match(canvas, /ui-designer-runtime-canvas-restart/)
  assert.match(inspector, /ui-designer-inspector-button-content/)
  assert.match(inspector, /ui-designer-inspector-button-\$\{field\.key\}/)
  assert.match(inspector, /ui-designer-inspector-button-events/)
  assert.match(buttonStates, /\['normal', 'hover', 'pressed', 'disabled'\]/)
  for (const suffix of ['preview', 'select', 'clear']) assert.match(buttonStates, new RegExp(`ui-designer-button-state-\\$\\{state\\}-${suffix}`))
  assert.match(events, /ui-designer-event-select/)
  assert.match(events, /ui-designer-event-action-add/)
  // gotoScene targets: opened scenes, project .mzui files, engine built-ins, plus free input.
  assert.match(events, /filterable allow-create default-first-option/)
  assert.match(events, /sceneTargetGroupOpen/)
  assert.match(events, /sceneTargetGroupProject/)
  assert.match(events, /sceneTargetGroupBuiltin/)
  assert.match(events, /UI_DESIGNER_BUILTIN_SCENE_NAMES/)
  assert.match(events, /builtinScenePurpose/)
  assert.match(events, /designer\.sceneFiles/)
  assert.match(property, /grid-template-columns: 82px minmax\(0, 1fr\) auto/)
  assert.match(property, /white-space: nowrap/)
  assert.match(settings, /class="settings-form"/)
  assert.match(settings, /\.inline-fields \{ display: flex; flex-wrap: nowrap/)
  assert.doesNotMatch(settings, /designer\.document\.meta\.sceneBase|UiNamedEntryField/)
  assert.match(sceneSettings, /designer\.document\.meta\.sceneName/)
  assert.match(sceneSettings, /UiNamedEntryField/)
  assert.match(openScene, /designer\.sceneFiles/)
  assert.match(saveAs, /isValidUiDesignerSceneName/)
  assert.doesNotMatch(shell, /runtimeInstallPromptTitle|applyProjectChanges|UiDesignerExportSurface/)
  assert.match(property, /ui-designer-resource-\$\{props\.fieldKey\}-select/)
  assert.match(property, /ui-designer-resource-\$\{props\.fieldKey\}-clear/)
  // JSON mode: toolbar toggle, dedicated panel, and editable apply path.
  assert.match(toolbar, /ui-designer-json-mode/)
  assert.match(toolbar, /emit\('editing-mode', mode\)/)
  assert.match(shell, /UiDesignerJsonPanel/)
  const jsonPanel = compile('./UiDesignerJsonPanel.vue')
  assert.match(jsonPanel, /ui-designer-json-panel/)
  assert.match(jsonPanel, /ui-designer-json-apply/)
  assert.match(jsonPanel, /designer\.applyJsonDocument\(draft\.value\)/)
  assert.match(jsonPanel, /mode="json"/)
})
