import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'
import { compileScript, parse } from '@vue/compiler-sfc'

const canvas = fs.readFileSync(new URL('./UiDesignerCanvas.vue', import.meta.url), 'utf8')
const fabricCanvas = fs.readFileSync(new URL('./UiDesignerFabricCanvas.vue', import.meta.url), 'utf8')
const fabricFactory = fs.readFileSync(new URL('../fabric/fabricNodeFactory.ts', import.meta.url), 'utf8')
const propertyField = fs.readFileSync(new URL('./UiPropertyField.vue', import.meta.url), 'utf8')
const nodePanel = fs.readFileSync(new URL('./UiDesignerNodePanel.vue', import.meta.url), 'utf8')
const shell = fs.readFileSync(new URL('./UiDesignerShell.vue', import.meta.url), 'utf8')
const toolbar = fs.readFileSync(new URL('./UiDesignerToolbar.vue', import.meta.url), 'utf8')
const sceneTabs = fs.readFileSync(new URL('./UiDesignerSceneTabs.vue', import.meta.url), 'utf8')
const hostLifecycle = fs.readFileSync(new URL('../composables/useUiDesignerRendererHost.ts', import.meta.url), 'utf8')
const previewWindow = fs.readFileSync(new URL('../composables/uiDesignerPreviewWindow.ts', import.meta.url), 'utf8')
const adapters = fs.readFileSync(new URL('../adapters.ts', import.meta.url), 'utf8')
const designerController = fs.readFileSync(new URL('../composables/useUiDesigner.ts', import.meta.url), 'utf8')
const routedView = fs.readFileSync(new URL('../../../views/UiDesignerView.vue', import.meta.url), 'utf8')
const canvasWorkspace = fs.readFileSync(new URL('../models/canvas-workspace.ts', import.meta.url), 'utf8')

const compileComponent = (name: string) => {
  const source = fs.readFileSync(new URL(name, import.meta.url), 'utf8')
  const parsed = parse(source, { filename: name })
  assert.deepEqual(parsed.errors, [])
  assert.doesNotThrow(() => compileScript(parsed.descriptor, { id: `canvas-authoring-${name}`, inlineTemplate: true }))
}

test('authoring canvas compiles with Fabric as the single design renderer', () => {
  for (const name of ['./UiDesignerCanvas.vue', './UiDesignerFabricCanvas.vue', './UiPropertyField.vue', './UiDesignerShell.vue', './UiDesignerExportSurface.vue', '../../../views/UiDesignerView.vue']) compileComponent(name)
  assert.equal(fs.existsSync(new URL('./UiCanvasNode.vue', import.meta.url)), false)
  assert.equal(fs.existsSync(new URL('./UiDesignerStaticNodePreview.vue', import.meta.url)), false)
})

test('UI designer keeps the isolated runtime only for explicit preview', () => {
  assert.match(canvas, /useUiDesignerRendererHost/)
  assert.match(canvas, /active: \(\) => rendererRequested\.value/)
  assert.match(canvas, /<UiDesignerFabricCanvas/)
  assert.doesNotMatch(canvas, /<iframe/)
  assert.match(canvas, /previewWindowHandle = openUiDesignerPreviewWindow/)
  assert.match(canvas, /rendererFrame\.value = previewWindowHandle\.frame/)
  assert.match(canvas, /onMessage: rendererHost\.onWindowMessage/)
  assert.match(canvas, /postMessage: \(message\) => previewWindowHandle\?\.postMessage\(message\) \?\? false/)
  assert.match(previewWindow, /window\.open\('about:blank', UI_DESIGNER_PREVIEW_WINDOW_NAME/)
  assert.match(previewWindow, /frame\.setAttribute\('sandbox', 'allow-scripts allow-same-origin'\)/)
  assert.match(previewWindow, /event\.source !== window\.opener[\s\S]*target\.contentWindow\.postMessage\(envelope\.message, '\*'\)/)
  assert.match(previewWindow, /preview\.postMessage\(\{ channel: UI_DESIGNER_PREVIEW_RELAY_CHANNEL, token: relayToken, message \}, '\*'\)/)
  assert.doesNotMatch(canvas, /UiCanvasNode|node-layer/)
  assert.match(canvas, /rendererFailureCode/)
  assert.match(canvas, /restartFailedPreview/)
  assert.match(canvas, /rendererDisconnected/)
  assert.match(canvas, /data-ui-id="ui-designer-runtime-canvas-restart"/)
  assert.match(fabricCanvas, /new Canvas\(element/)
  assert.match(fabricCanvas, /data-ui-id="ui-designer-fabric-canvas"/)
})

test('editor preview uses a separate live window while game preview launches an isolated game run', () => {
  assert.doesNotMatch(toolbar, /fullscreenPreview/)
  assert.match(toolbar, /ui-designer-preview-exit' : 'ui-designer-preview-enter/)
  assert.match(toolbar, /ui-designer-game-preview-exit' : 'ui-designer-game-preview-enter/)
  assert.match(toolbar, /canStartEditorPreview/)
  assert.match(toolbar, /:disabled="!designer\.isPreviewing && !designer\.canStartPreview"/)
  assert.match(toolbar, /gamePreview/)
  assert.match(shell, /<UiDesignerSceneTabs :designer="designer"/)
  assert.match(shell, /<UiDesignerInspector v-if="!showWelcome" ref="inspectorRef" :designer="designer"/)
  assert.doesNotMatch(shell, /fullscreenPreview/)
  assert.match(canvas, /<div class="canvas-toolbar">/)
  assert.match(canvas, /<div v-if="document\.canvas\.rulers" class="canvas-ruler horizontal"/)
  assert.match(canvas, /const rendererRequested = computed\(\(\) => editorPreviewing\.value/)
  assert.match(adapters, /api\.playtest\.start\(\{ project: project\.trim\(\), mode: 'ui_designer_scene', uiScene: scene \}\)/)
  assert.match(adapters, /if \(run\.mode === 'ui_designer_scene'\) callback/)
})

test('design and code keep one mounted Fabric canvas while editor preview starts lazily outside the shell', () => {
  assert.match(shell, /<template v-else>[\s\S]*UiDesignerCanvas[^>]*v-show="designer\.editingMode === 'design'"[\s\S]*UiDesignerCodePanel[^>]*v-show="designer\.editingMode === 'code'"/)
  assert.doesNotMatch(shell, /UiDesignerCanvas v-else-if/)
  assert.doesNotMatch(canvas, /ui-designer-canvas-refresh|rendererHost\.refreshCanvas/)
  assert.match(canvas, /const rendererRequested = computed\(\(\) => editorPreviewing\.value \|\| \(unwrap\(designer\.previewStatus\) === 'preparing' && unwrap\(designer\.previewExecutionMode\) === 'editor-preview'\)\)/)
  assert.match(hostLifecycle, /active\?: \(\) => boolean/)
  assert.match(hostLifecycle, /postMessage\?: \(message: UiDesignerRendererBridgeMessage\) => boolean/)
  assert.match(hostLifecycle, /if \(options\.postMessage\)[\s\S]*options\.postMessage\(message\)/)
  assert.match(hostLifecycle, /if \(rendererRequested\(\)\) void start\(\)/)
  assert.match(hostLifecycle, /const activeStop = watch\(rendererRequested/)
  assert.match(hostLifecycle, /else if \(session \|\| disposingSession \|\| retainedStaleSessions\.size\) \{\s*void dispose\('shutdown'\)/)
  const sceneWatcher = hostLifecycle.slice(hostLifecycle.indexOf('const sceneStop = watch('), hostLifecycle.indexOf('const draftStop = watch('))
  assert.match(sceneWatcher, /if \(rendererRequested\(\)\) syncScene\(sceneChanged\)/)
  assert.match(hostLifecycle, /if \(pendingMountRevision !== null\) \{\s*queueSceneSync\(forceMount\)/)
  assert.match(hostLifecycle, /const previewNeedsLatestMount = sceneSyncQueued && options\.executionMode\(\) !== 'authoring'/)
  assert.match(hostLifecycle, /syncScene\(previewNeedsLatestMount\)/)
  assert.match(hostLifecycle, /if \(!previewNeedsLatestMount\) options\.onExecutionModeReady/)
  const modeWatcher = hostLifecycle.slice(hostLifecycle.indexOf('const executionModeStop = watch('), hostLifecycle.indexOf('onMounted(() =>'))
  assert.match(modeWatcher, /syncScene\(true\)/)
  assert.match(modeWatcher, /status\.value === 'error' && !session && !disposingSession[\s\S]*void retry\(\)/)
  const previewStart = designerController.slice(designerController.indexOf('const startPreview ='), designerController.indexOf('const stopPreview ='))
  assert.ok(previewStart.indexOf('flushDrafts') < previewStart.indexOf('exportRuntimeDocument(document.value)'))
  assert.match(previewStart, /adapters\.gamePreview\.start/)
  assert.match(previewStart, /gamePreviewRunId = result\.value\.runId/)
  const editorPreviewStart = designerController.slice(designerController.indexOf('const startEditorPreview ='), designerController.indexOf('const stopEditorPreview ='))
  assert.ok(editorPreviewStart.indexOf('flushDrafts') < editorPreviewStart.indexOf("previewExecutionMode.value = 'editor-preview'"))
  assert.doesNotMatch(editorPreviewStart, /isEditorPreviewing\.value = true/)
  const previewReady = designerController.slice(designerController.indexOf('const acknowledgePreviewExecutionMode ='), designerController.indexOf('const failPreview ='))
  assert.match(previewReady, /if \(mode === 'editor-preview'\)/)
  assert.match(previewReady, /isEditorPreviewing\.value = true/)
  assert.doesNotMatch(previewReady, /full-preview/)
})

test('resource refresh follows an in-flight edit with the latest complete scene', () => {
  assert.match(hostLifecycle, /const sceneRevisionAtStart = revision[\s\S]*if \(revision !== sceneRevisionAtStart\) queueSceneSync\(true\)[\s\S]*postPendingResourceRefresh\(\)/)
})

test('renderer status stays transient while a terminal error remains restartable from authoring', () => {
  assert.doesNotMatch(canvas, /runtime-disabled/)
  assert.match(canvas, /rendererStatus === 'error' && unwrap\(designer\.previewStatus\) === 'error'[\s\S]*<template v-else-if="rendererRequested">[\s\S]*canvasSyncing/)
  assert.match(canvas, /\.canvas-panel \{ position: relative;/)
  assert.match(canvas, /\.canvas-runtime-state \{[^}]*top: 48px;[^}]*right: 8px;[^}]*pointer-events: none;/)
  assert.match(canvas, /\.canvas-runtime-state > span \{ min-width: 0; flex: 1 1 auto; \}/)
  assert.match(canvas, /\.canvas-runtime-state \.el-button \{ flex: 0 0 auto; pointer-events: auto; \}/)
})

test('renderer host does not settle a mounted receipt from the wrong execution mode', () => {
  const messageHandlerStart = hostLifecycle.indexOf('const onMessage =')
  const mountedHandler = hostLifecycle.slice(hostLifecycle.indexOf("if (message.kind === 'mounted'", messageHandlerStart), hostLifecycle.indexOf("if (message.kind === 'scene-state'", messageHandlerStart))
  assert.match(mountedHandler, /message\.payload\.executionMode === options\.executionMode\(\)/)
  assert.match(mountedHandler, /if \(!mountedModeMatches\)/)
  assert.match(mountedHandler, /pendingMountRevision = null/)
  assert.match(mountedHandler, /status\.value = 'loading'/)
  assert.match(mountedHandler, /syncScene\(true\)/)
})

test('pre-mount host scene-state does not become a protocol fatal after mount is queued', () => {
  const messageHandler = hostLifecycle.slice(hostLifecycle.indexOf('const onMessage ='), hostLifecycle.indexOf('const onIframeLoad ='))
  assert.match(messageHandler, /const sceneStateHasDocumentIdentity = sceneStatePayload\?\.mountedDocumentSceneId !== null/)
  assert.match(messageHandler, /candidateEnvelope\?\.kind === 'scene-state' && sceneStateHasDocumentIdentity/)
  assert.match(messageHandler, /candidateEnvelope\?\.kind === 'mounted' && \(pendingMountRevision !== null \|\| mountedDocumentSceneId\.value !== null\)/)
  assert.match(messageHandler, /sceneStateHasDocumentIdentity[\s\S]*minimumRevision: revision/)
})

test('renderer restart stops any retained owner before starting a replacement session', () => {
  const retryBlock = hostLifecycle.slice(hostLifecycle.indexOf('const retry ='), hostLifecycle.indexOf('function installMessageListener'))
  assert.match(retryBlock, /session \|\| disposingSession \|\| retainedStaleSessions\.size/)
  assert.match(retryBlock, /await dispose\('shutdown', 'shutdown', true\)/)
  assert.ok(retryBlock.indexOf("await dispose('shutdown'") < retryBlock.indexOf('await start()'))
})

test('authoring content uses Fabric objects while the runtime iframe belongs to the preview window', () => {
  assert.doesNotMatch(canvas, /<iframe/)
  assert.match(previewWindow, /document\.createElement\('iframe'\)/)
  assert.match(fabricFactory, /FabricImage|Textbox|createParticle|createProgress|createVideo/)
  assert.doesNotMatch(canvas, /authoring-frame|UiCanvasNode|resourcePreviewUrls/)
})

test('container and list focus retain the scope boundary and expose a visible way back', () => {
  assert.match(fabricFactory, /collectNodeSubtreeIds\(document, \[scopeNodeId\]\)/)
  assert.match(fabricFactory, /if \(scopeNodeId === 'node_root'\) scopedIds\.delete\(scopeNodeId\)/)
  assert.match(fabricFactory, /if \(left\.id === scopeNodeId\) return -1/)
  assert.match(canvas, /designer\.selectNodes\(node\.children\.length \? \[node\.children\[0\]\] : \[node\.id\]\)/)
  assert.match(canvas, /const exitContainer = \(\) => \{[\s\S]*editStack\.value = editStack\.value\.slice\(0, -1\)[\s\S]*designer\.selectNodes\(\[editingRootId\.value\]\)/)
  assert.match(canvas, /data-ui-id="ui-designer-container-scope"[\s\S]*data-ui-id="ui-designer-container-scope-exit"[\s\S]*@click="exitContainer"/)
  assert.match(canvas, /\.canvas-edit-breadcrumb \{[^}]*top: calc\(var\(--workspace-top, 0px\) \+ 8px\);[^}]*left: calc\(var\(--workspace-left, 0px\) \+ 8px\);/)
  assert.match(fabricCanvas, /props\.designer\.selectNodes\(ids\.length \? ids : \[props\.scopeNodeId\]\)/)
  assert.match(nodePanel, /primary\?\.type === 'container' \|\| primary\?\.type === 'list' \? primary\.id : primary\?\.parentId \?\? 'node_root'/)
  assert.match(canvas, /designer\.addNode\(nodeType, editingRootId\.value, worldFromClient\(event\)\)/)
})

test('the scene floats on an editable workspace and off-canvas content stays visible during a drag', () => {
  assert.match(canvas, /const WORKSPACE_MARGIN = 240/)
  assert.match(canvas, /resolveCanvasWorkspace\(document\.value, WORKSPACE_MARGIN, draftPositions\.value\)/)
  assert.match(canvasWorkspace, /includeRect\(nodeVisualRect\(node\)\)/)
  assert.match(canvasWorkspace, /draftPositions\[node\.id\]/)
  assert.match(canvas, /\.canvas-scene-frame \{[^}]*pointer-events: none;/)
  assert.match(canvas, /:style="\[sceneRectStyle, \{ backgroundColor: document\.canvas\.backgroundColor \}\]"/)
  assert.match(canvas, /:style="\[sceneRectStyle, \{ '--grid-size'/)
  assert.match(canvas, /:workspace="workspace"/)
  assert.match(fabricCanvas, /viewportTransform: \[1, 0, 0, 1, props\.workspace\.left, props\.workspace\.top\]/)
  assert.match(canvasWorkspace, /surface grows with node coordinates/)
  assert.match(canvasWorkspace, /Math\.max\(0, -minX\)/)
  assert.match(fabricFactory, /ancestor\.props\.clip && ancestor\.id !== 'node_root'/)
})

test('canvas interactions reject native selection and image dragging without blocking inline text editing', () => {
  assert.match(canvas, /@pointerdown\.capture="handleViewportPointerDown"/)
  assert.match(canvas, /@selectstart="preventNativeCanvasSelection"/)
  assert.match(canvas, /@dragstart="preventNativeCanvasDrag"/)
  assert.match(canvas, /window\.getSelection\(\)\?\.removeAllRanges\(\)/)
  assert.match(canvas, /\.canvas-viewport \{[^}]*user-select: none;[^}]*-webkit-user-select: none;[^}]*-webkit-user-drag: none;/)
  assert.match(fabricCanvas, /\.fabric-editor-canvas \{[^}]*user-select: none;[^}]*-webkit-user-select: none;[^}]*-webkit-user-drag: none;/)
  assert.match(fabricCanvas, /\.fabric-editor-canvas :deep\(textarea\) \{ user-select: text;/)
})

test('tree selection replaces stale Fabric controls even when selection synchronization overlaps', () => {
  assert.match(fabricCanvas, /let selectionSyncQueued = false/)
  assert.match(fabricCanvas, /if \(syncingSelection\) \{\s*selectionSyncQueued = true\s*return\s*\}/)
  assert.match(fabricCanvas, /if \(active && \(selected\.length !== 1 \|\| active !== selected\[0\]\)\) canvas\.discardActiveObject\(\)/)
  assert.match(fabricCanvas, /selected\.forEach\(\(object\) => object\.setCoords\(\)\)/)
  assert.match(fabricCanvas, /if \(!selectionSyncQueued\) return\s*selectionSyncQueued = false\s*syncFabricSelection\(\)/)
  const workspaceSyncStart = fabricCanvas.indexOf("watch(() => [props.workspace.width")
  const workspaceSync = fabricCanvas.slice(workspaceSyncStart, fabricCanvas.indexOf('\n\nonBeforeUnmount(() =>', workspaceSyncStart))
  assert.match(workspaceSync, /canvas\.setViewportTransform\(\[1, 0, 0, 1, left, top\]\)/)
  assert.match(workspaceSync, /for \(const object of objects\.values\(\)\) object\.setCoords\(\)/)
  assert.match(workspaceSync, /canvas\.getActiveObject\(\)\?\.setCoords\(\)/)
})

test('Fabric owns the generated canvas dimensions while the workspace expands', () => {
  assert.match(fabricCanvas, /canvas\.setDimensions\(\{ width, height \}\)/)
  assert.match(fabricCanvas, /<canvas ref="canvasElement" \/>/)
  assert.doesNotMatch(fabricCanvas, /<canvas[^>]*:(?:width|height)="workspace\.(?:width|height)"/)
  assert.doesNotMatch(
    fabricCanvas,
    /:deep\(\.(?:canvas-container|lower-canvas|upper-canvas)\)[^}]*\b(?:width|height):\s*100%\s*!important/,
  )
})

test('canvas pans only with Space plus left drag or middle drag and resizes freely unless Shift is held', () => {
  assert.match(canvas, /const spaceDrag = event\.button === 0 && spacePressed\.value/)
  assert.match(canvas, /if \(event\.button !== 1 && !spaceDrag\) return/)
  assert.match(fabricCanvas, /uniformScaling: false/)
  assert.match(fabricCanvas, /uniScaleKey: 'shiftKey'/)
  assert.match(fabricCanvas, /centeredKey: 'altKey'/)
  assert.match(fabricCanvas, /\(event\.e as MouseEvent\)\.shiftKey/)
  assert.match(fabricCanvas, /preserveAspect: shiftKey, fromCenter: altKey/)
  assert.match(fabricCanvas, /pointerStart: event\.e && Number\.isFinite\(event\.e\.clientX\)/)
  assert.match(fabricCanvas, /\(event\.clientX - state\.pointerStart\.x\) \/ zoom/)
  assert.match(fabricCanvas, /Math\.abs\(rawDelta\.x\) >= Math\.abs\(rawDelta\.y\) \? 'x' : 'y'/)
  assert.match(fabricCanvas, /previewSelectedPositionsWithSnap\(state\.nodeIds, state\.origins, delta, axisLock\)/)
  assert.match(fabricCanvas, /accumulateRotationDegrees\([\s\S]*state\.lastFabricRotation = wrappedAngle[\s\S]*state\.accumulatedRotation = accumulatedAngle/)
  assert.match(fabricCanvas, /canvas\.getScenePoint\(event\.e\)/)
  assert.match(fabricCanvas, /pointerResizeDelta\(node, state\.originRect, handle, pointer, altKey\)/)
  assert.match(fabricCanvas, /const drafts = unwrap\(props\.designer\.draftRects\)/)
  assert.match(fabricCanvas, /const positions = unwrap\(props\.designer\.draftPositions\)/)
  assert.match(fabricCanvas, /object\.setPositionByOrigin\(new Point\(draftPosition\.x, draftPosition\.y\)/)
  assert.match(fabricFactory, /centeredRotation: true/)
  assert.doesNotMatch(fabricFactory, /transformAnchorPoint/)
  assert.match(designerController, /previewNodeRotation = \(nodeId: string, rotation: number\)/)
  assert.match(designerController, /const commitDraftRotation = \(nodeId: string\)[\s\S]*node\.props\.rotate = normalizeGeometryInteger\(pendingRotation, node\.props\.rotate\)[\s\S]*'Rotate node'/)
})

test('sprite resource selection carries intrinsic dimensions into one controller transaction', () => {
  assert.match(designerController, /const setSpriteResource =/)
  assert.match(designerController, /const width = normalizeGeometryInteger\(dimensions\.width/)
  assert.match(designerController, /node\.props\.height = height/)
  assert.match(designerController, /const constrainsChildren = parent\?\.type === 'container' && parent\.props\.clip/)
  assert.match(designerController, /const fitScale = constrainsChildren \? Math\.min\(1, parentRect\.width \/ width, parentRect\.height \/ height\) : 1/)
  assert.match(designerController, /node\.props\.anchorX = 0\.5/)
  assert.match(designerController, /node\.props\.anchorY = 0\.5/)
  assert.match(designerController, /replaceActiveDocument\(next, 'Select sprite image'/)
})

test('nested nodes do not light every ancestor and parent bounds constrain transforms', () => {
  assert.match(fabricFactory, /const nodeAncestors =/)
  assert.match(fabricFactory, /ancestors\.some\(\(ancestor\) => ancestor\.locked\)/)
  assert.match(fabricFactory, /ancestors\.every\(\(ancestor\) => ancestor\.props\.visible\)/)
  assert.match(fabricFactory, /absolutePositioned: true/)
  assert.match(fabricFactory, /ancestor\.type === 'container' && ancestor\.props\.clip/)
  assert.match(fabricFactory, /const clipBoundary = \(width: number, height: number\) => boundary\(width, height, \{ fill: '#000000' \}\)/)
  assert.match(fabricFactory, /cropX,[\s\S]*cropY,[\s\S]*new Group\(\[boundary\(node\.props\.width, node\.props\.height\), image\]/)
  assert.doesNotMatch(fabricFactory, /group\.clipPath = clip/)
  assert.match(fabricFactory, /const clip = clipBoundary\(container\.props\.width, container\.props\.height\)/)
  assert.match(designerController, /clampNodePositionToParent/)
  assert.match(designerController, /clampNodeRectToParent/)
  assert.match(designerController, /collectNodeSubtreeIds/)
})

test('bounded number sliders keep both end thumbs inside the inspector column', () => {
  assert.match(propertyField, /\.number-control :deep\(\.el-slider\)[^{]*\{[^}]*box-sizing: border-box;[^}]*padding-inline: 10px;/)
})

test('multiline property inputs use the same full inspector control column as single-line inputs', () => {
  assert.match(propertyField, /\.property-field > \.el-input-number,\s*\.property-field > \.el-input,\s*\.property-field > \.el-textarea,[^{]*\{\s*grid-column: 2; grid-row: 1; width: 100%; min-width: 0;\s*\}/)
})

test('rapid project generations serialize disposal before the newest host start', () => {
  assert.match(hostLifecycle, /if \(disposePromise\) \{\s*if \(!coordinatePendingStarts \|\| disposeCoordinatesPendingStarts\) return disposePromise/)
  const disposeIndex = hostLifecycle.indexOf("await dispose('project-change', 'project-change', false)")
  const startIndex = hostLifecycle.indexOf('rendererAdapter.start(generation)')
  assert.ok(disposeIndex >= 0 && startIndex > disposeIndex)
  assert.match(hostLifecycle, /epoch !== startEpoch/)
  assert.match(hostLifecycle, /cancelMountedWatchdog = scheduleUiDesignerRendererHandshakeTimeout/)
  assert.match(hostLifecycle, /messageKind === 'receipt'/)
  assert.match(hostLifecycle, /messageKind === 'fatal'/)
  assert.doesNotMatch(hostLifecycle, /UI_RENDERER_CLIENT_FAILURE/)
  assert.match(hostLifecycle, /const fail = \(acceptedFailure: UiDesignerRendererFailure\)/)
  assert.match(hostLifecycle, /if \(failurePromise\) return failurePromise/)
  assert.match(hostLifecycle, /terminalGate\.accept\(message\)/)
  assert.doesNotMatch(hostLifecycle, /payload\.status === 'error'\) void fail/)
  assert.doesNotMatch(hostLifecycle, /error\.value = reason instanceof Error \? reason\.message/)
  assert.match(canvas, /rendererDisconnected/)
  assert.doesNotMatch(canvas, /rendererStage} \(\$\{rendererStageStatus/)
})

test('scene synchronization assigns fixed codes to export plan post snapshot and selection failures', () => {
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.sceneExport, stage\.value/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.updatePlan, stage\.value/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.mountPost, 'mount'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.patchPost, stage\.value/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.sceneSnapshot, stage\.value/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.selectionPost, stage\.value/)
  assert.doesNotMatch(hostLifecycle, /void fail\(reason\)|await fail\(reason\)/)
})

test('both ten second renderer watchdogs report distinct fixed codes and stages', () => {
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.handshakeTimeout, stage\.value/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.mountedTimeout, 'mounted'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.handshakeWatchdog, 'iframe-load'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.mountedWatchdog, 'mounted'/)
})

test('authenticated pre-mount progress renews the handshake watchdog without extending mounted waits', () => {
  assert.match(hostLifecycle, /const armHandshakeWatchdog = \(activeSessionId: string\): boolean =>/)
  assert.match(hostLifecycle, /session\?\.sessionId === activeSessionId && pendingMountRevision === null && !executionModeReady\.value/)
  assert.match(hostLifecycle, /const advancesHandshake = messageKind === 'receipt'[\s\S]*messageKind === 'hello'[\s\S]*messageKind === 'ready'[\s\S]*messageKind === 'scene-state' && !sceneStateHasDocumentIdentity/)
  assert.match(hostLifecycle, /if \(advancesHandshake\) acknowledgeIframeLoad\(\)/)
  assert.match(hostLifecycle, /if \(advancesHandshake && pendingMountRevision === null && !executionModeReady\.value && !armHandshakeWatchdog\(active\.sessionId\)\) return/)
  assert.match(hostLifecycle, /pendingMountRevision = revision[\s\S]*cancelHandshake\(\)/)
})

test('authenticated iframe progress closes the DOM load-event race before scene mounting', () => {
  assert.match(hostLifecycle, /const acknowledgeIframeLoad = \(\) => \{[\s\S]*iframeLoaded = true[\s\S]*if \(firstAcknowledgement\) maybeRun\(\)/)
  assert.match(hostLifecycle, /if \(advancesHandshake\) acknowledgeIframeLoad\(\)/)
  assert.match(hostLifecycle, /const onIframeLoad = \(\) => \{\s*acknowledgeIframeLoad\(\)\s*\}/)
})

test('authenticated fixed pre-mount scene state closes the one-shot ready race', () => {
  assert.match(hostLifecycle, /const acknowledgeEngineReady = \(reportedEngineSceneClass: string\) => \{[\s\S]*reportedEngineSceneClass !== UI_DESIGNER_RENDERER_HOST_SCENE_CLASS[\s\S]*engineReady = true[\s\S]*maybeRun\(\)/)
  assert.match(hostLifecycle, /message\.kind === 'ready'[\s\S]*acknowledgeEngineReady\(message\.payload\.engineSceneClass\)/)
  assert.match(hostLifecycle, /message\.kind === 'scene-state'[\s\S]*!engineReady[\s\S]*message\.payload\.phase === 'active'[\s\S]*message\.payload\.actualScene === UI_DESIGNER_RENDERER_HOST_SCENE_CLASS[\s\S]*message\.payload\.engineSceneClass === UI_DESIGNER_RENDERER_HOST_SCENE_CLASS[\s\S]*message\.payload\.mountedDocumentSceneId === null[\s\S]*message\.payload\.documentSceneName === null[\s\S]*message\.payload\.revision === 0[\s\S]*message\.payload\.executionMode === 'authoring'[\s\S]*acknowledgeEngineReady\(message\.payload\.engineSceneClass\)/)
})

test('start confirm and iframe terminals enter the shared latch with fixed safe codes', () => {
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.startAdapter, 'start'/)
  assert.match(hostLifecycle, /resolveUiDesignerRendererFailure\(UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.startResult, 'start'\)/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.confirmIpc, 'confirm'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.confirmIdentity, 'confirm'/)
  assert.match(hostLifecycle, /UI_DESIGNER_RENDERER_LOCAL_FAILURE_CODES\.iframeLoad, 'iframe-load'/)
  assert.match(hostLifecycle, /if \(terminalFailure\) void fail\(terminalFailure\)/)
  assert.match(hostLifecycle, /void fail\(resolveUiDesignerRendererFailure\('UI_RENDERER_BRIDGE_PROTOCOL', stage\.value\)\)/)
  const startAndConfirm = hostLifecycle.slice(hostLifecycle.indexOf('const start = async'), hostLifecycle.indexOf('const messageOriginMatches'))
  assert.doesNotMatch(startAndConfirm, /result\.message/)
  assert.match(canvas, /:data-failure-code="rendererFailureCode \|\| undefined"/)
  assert.match(canvas, /:data-failure-stage="rendererStage"/)
  assert.match(canvas, /const rendererFailureMessage = computed\(\(\) => t\('rendererDisconnected'\)\)/)
  assert.match(canvas, /rendererStatus === 'error' && unwrap\(designer\.previewStatus\) === 'error'/)
  assert.match(canvas, /<template v-else-if="rendererRequested">/)
  assert.match(canvas, /const restartFailedPreview = \(\) => designer\.startEditorPreview\(\)/)
  assert.match(canvas, /@click="restartFailedPreview"/)
  assert.doesNotMatch(canvas, /@click="rendererHost\.retry\(\)"/)
})

test('preview failure details stay opt-in, bounded, and separate from the Fabric canvas renderer', () => {
  assert.match(hostLifecycle, /const failureDetails = ref<UiDesignerRendererFailureDetails \| null>\(null\)/)
  assert.match(hostLifecycle, /failureDetails\.value = \{[\s\S]*iframeLoaded,[\s\S]*engineReady,[\s\S]*processConfirmed,[\s\S]*pendingMountRevision,[\s\S]*lastHostMessageKind,[\s\S]*cleanupConfirmed: null/)
  assert.match(hostLifecycle, /sanitizeRendererTechnicalMessage[\s\S]*\.slice\(0, 1024\)/)
  assert.match(canvas, /class="renderer-details-button" data-ui-id="ui-designer-runtime-canvas-details"[\s\S]*rendererFailureDetailsVisible = true/)
  const detailsButton = canvas.slice(canvas.indexOf('class="renderer-details-button"'), canvas.indexOf('</el-button>', canvas.indexOf('class="renderer-details-button"')))
  assert.doesNotMatch(detailsButton, /\stext(?:\s|>)/)
  assert.match(detailsButton, /t\('errorDetails'\)/)
  assert.match(canvas, /<el-dialog[\s\S]*data-ui-id="ui-designer-runtime-canvas-details-content"[\s\S]*rendererFailureDetailsText/)
  assert.match(canvas, /<UiDesignerFabricCanvas/)
  assert.doesNotMatch(canvas, /UiCanvasNode|node-layer/)
})

test('canvas exposes bounded renderer lifecycle diagnostics to the hidden desktop bridge', () => {
  assert.match(canvas, /data-ui-id="ui-designer-canvas"/)
  assert.match(canvas, /:data-renderer-status="rendererStatus"/)
  assert.match(canvas, /:data-renderer-stage="rendererStage"/)
  assert.match(canvas, /:data-renderer-failure-code="rendererFailureCode \|\| undefined"/)
  assert.match(canvas, /:data-preview-status="unwrap\(designer\.previewStatus\)"/)
  assert.match(canvas, /:data-preview-mode="requestedExecutionMode"/)
  assert.match(canvas, /:data-renderer-execution-mode="rendererHost\.executionMode\.value"/)
  assert.match(canvas, /:data-renderer-mode-ready="rendererHost\.executionModeReady\.value \? 'true' : 'false'"/)
})

test('stale renderer starts keep an opaque owner for a retryable stop', () => {
  assert.match(hostLifecycle, /retainedStaleSessions/)
  assert.match(hostLifecycle, /const stopStaleSession = async/)
  assert.match(hostLifecycle, /await stopStaleSession\(result\.value, rendererAdapter\)/)
  assert.match(hostLifecycle, /retainedStopPromise/)
  assert.match(hostLifecycle, /if \(!stopped && \(!session \|\| session\.sessionId === result\.value\.sessionId\)\)/)
  assert.match(hostLifecycle, /onExecutionModeError\?\.\(error\.value, true\)/)
  assert.doesNotMatch(hostLifecycle, /if \(.*stale.*\)\s*session = result\.value/)
  assert.match(hostLifecycle, /previous isolated UI canvas session was kept/)
})

test('renderer scene sync waits for the iframe handshake and mounted revision', () => {
  assert.match(hostLifecycle, /!engineReady \|\| !processConfirmed \|\| !iframeLoaded/)
  const pendingMountGate = hostLifecycle.indexOf('if (pendingMountRevision !== null) {')
  const nextRevision = hostLifecycle.indexOf('revision = update.revision', pendingMountGate)
  assert.ok(pendingMountGate >= 0 && nextRevision > pendingMountGate)
  assert.match(hostLifecycle, /post\('mount',[\s\S]*pendingMountRevision = revision/)
  assert.match(hostLifecycle, /message\.kind === 'mounted'[\s\S]*pendingMountRevision = null[\s\S]*syncScene\(previewNeedsLatestMount\)/)
  assert.match(hostLifecycle, /!executionModeReady\.value/)
  assert.match(hostLifecycle, /update\.kind === 'patch' && !executionModeReady\.value/)
  assert.match(hostLifecycle, /iframeLoaded = true[\s\S]*maybeRun\(\)/)
  assert.match(hostLifecycle, /options\.designer\.runtimeDiagnostics = \[\]/)
})

test('editor preview follows scene changes while a captured game preview keeps scene tabs locked', () => {
  assert.match(sceneTabs, /if \(designer\.isPreviewing\) return/)
  assert.match(designerController, /const activateScene = \(sceneId: string\) => \{\s*if \(previewOccupied\.value && previewExecutionMode\.value !== 'editor-preview' && !isEditorPreviewing\.value\) return false/)
  const contextBarrier = designerController.indexOf('const previewWasOccupied = previewOccupied.value')
  const contextDiscardPrompt = designerController.indexOf('options.confirmDiscard()', contextBarrier)
  assert.ok(contextBarrier >= 0 && contextDiscardPrompt > contextBarrier)
})

test('route teardown waits for the renderer owner before leaving the designer', () => {
  assert.match(routedView, /disposePreview\('unload'\)/)
  assert.match(routedView, /if \(shellRef\.value && !\(await shellRef\.value\.disposePreview\('unload'\)\)\) return false/)
  assert.match(shell, /if \(rawDesigner\.isEditorPreviewing\.value\) rawDesigner\.stopEditorPreview\(\)/)
  assert.match(shell, /if \(rawDesigner\.isPreviewing\.value\) rawDesigner\.stopPreview\(\)/)
  assert.match(shell, /void rawDesigner\.disposePreview\('unload'\)/)
})

test('window close consults the renderer lifecycle instead of the beforeunload veto', () => {
  const preload = fs.readFileSync(new URL('../../../../electron/preload.ts', import.meta.url), 'utf8')
  const main = fs.readFileSync(new URL('../../../../electron/main.ts', import.meta.url), 'utf8')
  const ipcHandlers = fs.readFileSync(new URL('../../../../electron/ipc-handlers.ts', import.meta.url), 'utf8')
  assert.match(preload, /ipcRenderer\.on\('app:close-request', listener\)/)
  assert.match(preload, /ipcRenderer\.send\('app:close-guard', \{ registered: true \}\)/)
  assert.match(preload, /ipcRenderer\.send\('app:close-response', \{ proceed \}\)/)
  assert.match(ipcHandlers, /ipcMain\.on\('app:close-guard', onRendererCloseGuardRegistration\)/)
  assert.match(ipcHandlers, /export function requestRendererCloseResolution/)
  assert.match(main, /const rendererProceed = await requestRendererCloseResolution\(win\)/)
  assert.match(main, /frameName !== 'rpg-agent-ui-designer-preview'[\s\S]*useContentSize: true,[\s\S]*paintWhenInitiallyHidden: true/)
  assert.match(main, /if \(closeGuardRunning\) \{\s*void offerForceClose\(mainWindow\)/)
  assert.match(main, /win\.destroy\(\)/)
  assert.match(routedView, /:lifecycle-adapter="lifecycleAdapter"/)
  assert.match(routedView, /window\.api\?\.lifecycle\?\.onCloseRequest/)
  assert.match(routedView, /guard\.confirmDiscard \? await guard\.confirmDiscard\(\) : false/)
})

test('scene-state fatal keeps the route barrier on one active owner and retries backend cleanup', () => {
  assert.match(hostLifecycle, /if \(session \|\| disposingSession\) actorDisposed = true/)
  assert.match(hostLifecycle, /if \(!actorTerminal && actorDisposed\) actorTerminal = true/)
  assert.match(hostLifecycle, /if \(messageKind === 'fatal'\) \{[\s\S]*terminalGate\.accept\(message\)[\s\S]*actorDisposed = true\s*pendingDispose\?\.acknowledge\(\)/)
  assert.match(hostLifecycle, /onExecutionModeError\?\.\(recoveryReason, !terminal\)/)
  // Terminal editor-preview failures must notify the designer too; gating the
  // call on full-preview left previewStatus stuck on 'preparing'.
  assert.doesNotMatch(hostLifecycle, /'full-preview' \|\| !terminal\) options\.onExecutionModeError/)
  assert.match(designerController, /const previewCleanupPending = ref\(false\)/)
  assert.match(designerController, /previewCleanupPending\.value \|\| previewDisposalInFlight\.value \|\| previewStatus\.value === 'preparing'/)
  assert.match(designerController, /failPreview = \(message = '', cleanupPending = false\)/)
})

test('terminal retry preserves the fixed cause through cleanup and resets only before a new owner starts', () => {
  assert.match(hostLifecycle, /const outcome = failureLatch\.accept\(candidate\)[\s\S]*if \(outcome\.accepted\) \{\s*failureCode\.value = outcome\.failure\.code\s*failureRecoveryReason\.value = outcome\.failure\.recoveryReason/)
  assert.match(hostLifecycle, /const authoritativeFailure = latchFailure\(acceptedFailure\)/)
  assert.match(hostLifecycle, /if \(terminalFailure\) latchFailure\(terminalFailure\)/)
  assert.match(hostLifecycle, /const terminal = await dispose\('shutdown', 'protocol-error', false\)/)
  assert.match(hostLifecycle, /console\.error\('\[ui-designer renderer bridge failure\]', \{\s*code: authoritativeFailure\.code,\s*stage: failedStage,\s*cleanupConfirmed: terminal,/)
  const cleanupBarrier = hostLifecycle.indexOf("if (!await stopRetainedStaleSessions())")
  const gateReset = hostLifecycle.indexOf('terminalGate.reset()', cleanupBarrier)
  const rendererStart = hostLifecycle.indexOf('rendererAdapter.start(generation)', gateReset)
  assert.ok(cleanupBarrier >= 0 && gateReset > cleanupBarrier && rendererStart > gateReset)
  assert.match(hostLifecycle, /failureCode\.value = null\s*failureRecoveryReason\.value = ''/)
})

test('stop failures preserve a retryable disposer through unmount', () => {
  assert.match(hostLifecycle, /void dispose\('unload'\)\s*\.then\(\(barrierOk\) =>/)
  assert.match(hostLifecycle, /pendingStarts\.add\(pendingStart\)/)
  assert.match(hostLifecycle, /pendingStarts\.delete\(pendingStart\)/)
  assert.match(hostLifecycle, /pendingStartCleanup = true\s*await waitForPendingStarts\(\)/)
  assert.match(hostLifecycle, /if \(pendingStartCleanup\) return true/)
  assert.match(hostLifecycle, /const currentOk = await currentDispose\s*await waitForPendingStarts\(\)/)
  assert.match(hostLifecycle, /if \(disposed && coordinatePendingStarts\)/)
  assert.match(hostLifecycle, /if \(pendingStartCleanup \|\| queuedDisposePromise \|\| disposeCoordinatesPendingStarts\) return/)
  assert.match(hostLifecycle, /if \(barrierOk\) \{[\s\S]*unregisterPreviewDisposer\(\)[\s\S]*removeMessageListener\(\)/)
  assert.doesNotMatch(hostLifecycle, /\.finally\(unregisterPreviewDisposer\)/)
})

test('project and route cleanup await active and retained owners before terminal success', () => {
  const activeStop = hostLifecycle.indexOf('await stopBackend(active, backendReason, activeAdapter)')
  const retainedStop = hostLifecycle.indexOf('if (!await stopRetainedStaleSessions())', activeStop)
  const authoringReady = hostLifecycle.indexOf("options.onExecutionModeReady?.('authoring')", retainedStop)
  const terminalSuccess = hostLifecycle.indexOf('return true', authoringReady)
  assert.ok(activeStop >= 0 && retainedStop > activeStop)
  assert.ok(authoringReady > retainedStop && terminalSuccess > authoringReady)
  assert.match(hostLifecycle, /if \(!await stopRetainedStaleSessions\(\)\) \{\s*status\.value = 'error'[\s\S]*return false/)
  assert.match(hostLifecycle, /if \(!active\) \{\s*const ok = await stopRetainedStaleSessions\(\)/)
  assert.match(hostLifecycle, /stopBackend\(owner\.session, 'project-change', owner\.adapter\)/)
  assert.match(designerController, /const previewDisposalInFlight = ref\(false\)/)
  assert.match(designerController, /if \(previewDisposePromise\) return previewDisposePromise/)
  assert.match(designerController, /previewCleanupPending\.value \|\| previewDisposalInFlight\.value/)
  assert.match(shell, /previewDisposalInFlight\.value/)
  assert.match(routedView, /previewDisposalInFlight/)
})

test('external previews keep the existing Element Plus tree owner mounted', () => {
  assert.match(nodePanel, /defineExpose\(\{ getExpandedKeys, setExpandedKeys \}\)/)
  assert.match(nodePanel, /@node-expand="rememberExpanded"/)
  assert.match(nodePanel, /@node-collapse="rememberCollapsed"/)
  assert.match(nodePanel, /type === 'before' \|\| type === 'prev'/)
  assert.match(nodePanel, /type === 'after' \|\| type === 'next'/)
  assert.match(shell, /<UiDesignerNodePanel :designer="designer"/)
  assert.doesNotMatch(shell, /nodePanelRef|expandedNodeIds|fullscreenPreview/)
})

test('project publishing reviews staged files before applying them', () => {
  assert.match(shell, /runtimeInstallPromptTitle/)
  assert.match(shell, /await rawDesigner\.checkRuntime\(\)/)
  assert.match(shell, /props\.applyProjectChanges\?\./)
  assert.match(routedView, /mapsApi\.projectStaging\(project\)/)
  assert.match(routedView, /collectStagedFiles\(status, fallbackFiles\)/)
  assert.match(routedView, /ElMessageBox\.confirm\(/)
  assert.match(routedView, /mapsApi\.applyProjectStaging\(/)
})
