import type { ProductLanguage } from '@contract/types';
import { pickByLocale } from '../i18n/messages.ts';
import type { CommandDefinition, CommandField } from '../composables/eventCommandCatalog';

type CommandGroup = { group: string; items: CommandDefinition[] };

const COMMAND_LABELS_BY_LOCALE: Record<ProductLanguage, Record<number, string>> = {
  'zh-CN': {},
  'en-US': {
    101: 'Show Text',
    102: 'Show Choices',
    103: 'Input Number',
    104: 'Select Item',
    105: 'Show Scrolling Text',
    108: 'Comment',
    111: 'Conditional Branch',
    112: 'Loop',
    113: 'Break Loop',
    115: 'Exit Event Processing',
    117: 'Common Event',
    118: 'Label',
    119: 'Jump to Label',
    121: 'Control Switches',
    122: 'Control Variables',
    123: 'Control Self Switch',
    124: 'Control Timer',
    125: 'Change Gold',
    126: 'Change Items',
    127: 'Change Weapons',
    128: 'Change Armors',
    129: 'Change Party Member',
    132: 'Change Battle BGM',
    133: 'Change Victory ME',
    134: 'Change Save Access',
    135: 'Change Menu Access',
    136: 'Change Encounter',
    137: 'Change Formation Access',
    138: 'Change Window Color',
    139: 'Change Defeat ME',
    140: 'Change Vehicle BGM',
    201: 'Transfer Player',
    202: 'Set Vehicle Location',
    203: 'Set Event Location',
    204: 'Scroll Map',
    205: 'Set Movement Route',
    206: 'Get on/off Vehicle',
    211: 'Change Transparency',
    212: 'Show Animation',
    213: 'Show Balloon Icon',
    214: 'Erase Event',
    216: 'Change Player Followers',
    217: 'Gather Followers',
    221: 'Fadeout Screen',
    222: 'Fadein Screen',
    223: 'Tint Screen',
    224: 'Flash Screen',
    225: 'Shake Screen',
    230: 'Wait',
    231: 'Show Picture',
    232: 'Move Picture',
    233: 'Rotate Picture',
    234: 'Tint Picture',
    235: 'Erase Picture',
    236: 'Set Weather Effect',
    241: 'Play BGM',
    242: 'Fadeout BGM',
    243: 'Save BGM',
    244: 'Replay BGM',
    245: 'Play BGS',
    246: 'Fadeout BGS',
    249: 'Play ME',
    250: 'Play SE',
    251: 'Stop SE',
    261: 'Play Movie',
    281: 'Change Map Name Display',
    282: 'Change Tileset',
    283: 'Change Battleback',
    284: 'Change Parallax',
    285: 'Get Location Info',
    301: 'Battle Processing',
    302: 'Shop Processing',
    303: 'Name Input Processing',
    311: 'Change HP',
    312: 'Change MP',
    313: 'Change State',
    314: 'Recover All',
    315: 'Change EXP',
    316: 'Change Level',
    317: 'Change Parameter',
    318: 'Change Skill',
    319: 'Change Equipment',
    320: 'Change Name',
    321: 'Change Class',
    322: 'Change Actor Images',
    323: 'Change Vehicle Image',
    324: 'Change Nickname',
    325: 'Change Profile',
    326: 'Change TP',
    331: 'Change Enemy HP',
    332: 'Change Enemy MP',
    333: 'Change Enemy State',
    334: 'Enemy Recover All',
    335: 'Enemy Appear',
    336: 'Enemy Transform',
    337: 'Show Battle Animation',
    339: 'Force Action',
    340: 'Abort Battle',
    342: 'Change Enemy TP',
    351: 'Open Menu Screen',
    352: 'Open Save Screen',
    353: 'Game Over',
    354: 'Return to Title Screen',
    355: 'Script',
    356: 'Plugin Command',
  },
};

const COMMAND_TEXT_BY_SOURCE_LABEL_BY_LOCALE: Record<ProductLanguage, Record<string, string>> = {
  'zh-CN': {},
  'en-US': {
  '消息': 'Message',
  '游戏进程': 'Game Progression',
  '流程控制': 'Flow Control',
  '队伍': 'Party',
  '角色': 'Actor',
  '移动': 'Movement',
  '人物': 'Character',
  '图片': 'Picture',
  '等待': 'Wait',
  '画面': 'Screen',
  '音频和视频': 'Audio & Video',
  '场景控制': 'Scene Control',
  '系统设置': 'System Settings',
  '地图': 'Map',
  '战斗': 'Battle',
  '高级': 'Advanced',
  '文件': 'File',
  '音量': 'Volume',
  '音调': 'Pitch',
  '声像': 'Pan',
  '操作': 'Operation',
  '值类型': 'Value Type',
  '值': 'Value',
  '常量': 'Constant',
  '变量': 'Variable',
  '操作数类型': 'Operand Type',
  '随机最小值': 'Random Min',
  '随机最大值': 'Random Max',
  '游戏数据': 'Game Data',
  '数据参数 1': 'Data Parameter 1',
  '数据参数 2': 'Data Parameter 2',
  '脚本': 'Script',
  '目标类型': 'Target Type',
  '队伍位置': 'Party Position',
  '位数': 'Digits',
  '物品类型': 'Item Type',
  '起始开关': 'Start Switch',
  '结束开关': 'End Switch',
  '起始变量': 'Start Variable',
  '结束变量': 'End Variable',
  '独立开关': 'Self Switch',
  '秒数': 'Seconds',
  '公共事件': 'Common Event',
  '名称': 'Name',
  '物品': 'Item',
  '武器': 'Weapon',
  '防具': 'Armor',
  '包含装备': 'Include Equipment',
  '初始化': 'Initialize',
  '允许死亡': 'Allow Knockout',
  '显示升级': 'Show Level Up',
  '能力值': 'Parameter',
  '装备类型': 'Equipment Type',
  '装备 ID': 'Equipment ID',
  '名字': 'Name',
  '职业': 'Class',
  '保留等级': 'Keep Level',
  '昵称': 'Nickname',
  '简介': 'Profile',
  '位置指定': 'Location',
  'X 变量': 'X Variable',
  'Y 变量': 'Y Variable',
  '地图变量': 'Map Variable',
  '朝向': 'Direction',
  '淡入淡出': 'Fade',
  '目标 ID': 'Target ID',
  '交换目标 ID': 'Exchange Target ID',
  '写入变量': 'Destination Variable',
  '信息类型': 'Info Type',
  '敌群指定': 'Troop',
  '敌群': 'Troop',
  '敌群变量': 'Troop Variable',
  '允许逃跑': 'Can Escape',
  '允许失败': 'Can Lose',
  '商品类型': 'Goods Type',
  '价格类型': 'Price Type',
  '价格': 'Price',
  '仅购买': 'Purchase Only',
  '图片编号': 'Picture ID',
  '原点': 'Origin',
  '横向缩放': 'Width Scale',
  '纵向缩放': 'Height Scale',
  '不透明度': 'Opacity',
  '合成方式': 'Blend Mode',
  '红': 'Red',
  '绿': 'Green',
  '蓝': 'Blue',
  '灰度': 'Gray',
  '强度': 'Power',
  '方向': 'Direction',
  '距离': 'Distance',
  '速度': 'Speed',
  '等待结束': 'Wait for Completion',
  '镜像': 'Mirror',
  '透明': 'Transparency',
  '队列行进': 'Followers',
  '动画': 'Animation',
  '气泡': 'Balloon',
  '持续帧数': 'Duration',
  '天气': 'Weather',
  '帧数': 'Frames',
  '影片': 'Movie',
  '最大字数': 'Max Characters',
  '交通工具': 'Vehicle',
  '存档': 'Save',
  '菜单': 'Menu',
  '遇敌': 'Encounter',
  '队形': 'Formation',
  '角色图': 'Character Sprite',
  '角色图索引': 'Character Sprite Index',
  '脸图': 'Face Graphic',
  '脸图索引': 'Face Index',
  '战斗图': 'Battler Graphic',
  '索引': 'Index',
  '地图名称': 'Map Name',
  '图块组': 'Tileset',
  '背景 1': 'Background 1',
  '背景 2': 'Background 2',
  '远景': 'Parallax',
  '横向循环': 'Loop Horizontally',
  '纵向循环': 'Loop Vertically',
  '横向滚动': 'Horizontal Scroll',
  '纵向滚动': 'Vertical Scroll',
  '敌人序号': 'Enemy Index',
  '敌人': 'Enemy',
  '敌人条件': 'Enemy Condition',
  '敌人状态': 'Enemy State',
  '主体类型': 'Subject Type',
  '主体编号': 'Subject ID',
  '技能': 'Skill',
  '目标序号': 'Target Index',
  '命令': 'Command',
  '条件类型': 'Condition Type',
  '开关': 'Switch',
  '开关值': 'Switch Value',
  '比较对象': 'Compare To',
  '比较变量': 'Comparison Variable',
  '比较': 'Comparison',
  '独立开关值': 'Self Switch Value',
  '计时器比较': 'Timer Comparison',
  '角色条件': 'Actor Condition',
  '状态': 'State',
  '金钱': 'Gold',
  '金钱比较': 'Gold Comparison',
  '按键': 'Button',
  '黑': 'Black',
  '白': 'White',
  '无': 'None',
  '普通': 'Normal',
  '暗淡': 'Dim',
  '窗口': 'Window',
  '顶部': 'Top',
  '中部': 'Middle',
  '底部': 'Bottom',
  '允许': 'Enable',
  '禁止': 'Disable',
  '增加': 'Increase',
  '减少': 'Decrease',
  '随机数': 'Random',
  '固定角色': 'Fixed Actor',
  '队伍角色': 'Party Member',
  '保持': 'Retain',
  '下': 'Down',
  '左': 'Left',
  '右': 'Right',
  '上': 'Up',
  '小船': 'Boat',
  '大船': 'Ship',
  '飞艇': 'Airship',
  '直接指定': 'Direct Designation',
  '变量指定': 'Designation with Variables',
  '与角色/事件交换': 'Exchange with Another Event',
  '左上': 'Upper Left',
  '中心': 'Center',
  '加法': 'Additive',
  '乘法': 'Multiply',
  '滤色': 'Screen',
  '物品持有数': 'Item Count',
  '武器持有数': 'Weapon Count',
  '防具持有数': 'Armor Count',
  '角色数据': 'Actor Data',
  '敌人数据': 'Enemy Data',
  '角色/事件位置': 'Character/Event Position',
  '队伍成员': 'Party Member',
  '其他数据': 'Other Data',
  '计时器': 'Timer',
  '角色/事件朝向': 'Character/Event Direction',
  '在队伍中': 'In the Party',
  '出现': 'Appeared',
  '以上': 'or Above',
  '以下': 'or Below',
  '小于': 'Less than',
  '普通物品': 'Regular Item',
  '关键物品': 'Key Item',
  '隐藏物品 A': 'Hidden Item A',
  '隐藏物品 B': 'Hidden Item B',
  '代入': 'Set',
  '加算': 'Add',
  '减算': 'Sub',
  '乘算': 'Mul',
  '除算': 'Div',
  '取余': 'Mod',
  '开始': 'Start',
  '停止': 'Stop',
  '加入': 'Add',
  '离开': 'Remove',
  '附加': 'Add',
  '解除': 'Remove',
  '最大 HP': 'Max HP',
  '最大 MP': 'Max MP',
  '攻击力': 'Attack',
  '防御力': 'Defense',
  '魔法力': 'Magic Attack',
  '魔法防御': 'Magic Defense',
  '敏捷': 'Agility',
  '幸运': 'Luck',
  '学会': 'Learn',
  '忘记': 'Forget',
  '惊叹': 'Exclamation',
  '问号': 'Question',
  '音符': 'Music Note',
  '爱心': 'Heart',
  '愤怒': 'Anger',
  '汗': 'Sweat',
  '纠结': 'Frustration',
  '沉默': 'Silence',
  '灯泡': 'Light Bulb',
  '雨': 'Rain',
  '暴风雨': 'Storm',
  '雪': 'Snow',
  '显示': 'Show',
  '隐藏': 'Hide',
  '地形标记': 'Terrain Tag',
  '事件编号': 'Event ID',
  '图块编号（层 1）': 'Tile ID (Layer 1)',
  '图块编号（层 2）': 'Tile ID (Layer 2)',
  '图块编号（层 3）': 'Tile ID (Layer 3)',
  '区域编号': 'Region ID',
  '与地图遇敌相同': 'Same as Random Encounter',
  '数据库价格': 'Standard Price',
  '指定价格': 'Specified Price',
  },
};

export function localizeCommandCodeLabel(code: number, language: ProductLanguage, fallback?: string): string {
  return pickByLocale(language, {
    'zh-CN': () => fallback || `Raw command ${code}`,
    'en-US': () => COMMAND_LABELS_BY_LOCALE['en-US'][code] || `Command ${code}`,
  })();
}

export function localizeCommandLabel(definition: CommandDefinition, language: ProductLanguage): string {
  return localizeCommandCodeLabel(definition.code, language, definition.label);
}

export function localizeCommandText(label: string, language: ProductLanguage): string {
  return pickByLocale(language, {
    'zh-CN': label,
    'en-US': COMMAND_TEXT_BY_SOURCE_LABEL_BY_LOCALE['en-US'][label] || label,
  });
}

export function localizeCommandField(field: CommandField, language: ProductLanguage): CommandField {
  return pickByLocale<() => CommandField>(language, {
    'zh-CN': () => field,
    'en-US': () => ({
      ...field,
      label: localizeCommandText(field.label, language),
      options: field.options?.map(([value, label]) => [value, localizeCommandText(label, language)]),
    }),
  })();
}

export function localizeCommandDefinition(definition: CommandDefinition, language: ProductLanguage): CommandDefinition {
  return pickByLocale<() => CommandDefinition>(language, {
    'zh-CN': () => definition,
    'en-US': () => ({
      ...definition,
      label: localizeCommandLabel(definition, language),
      group: localizeCommandText(definition.group, language),
      fields: definition.fields.map((field) => localizeCommandField(field, language)),
    }),
  })();
}

export function localizeCommandGroups(groups: CommandGroup[], language: ProductLanguage): CommandGroup[] {
  return pickByLocale<() => CommandGroup[]>(language, {
    'zh-CN': () => groups,
    'en-US': () => groups.map((group) => ({
      group: localizeCommandText(group.group, language),
      items: group.items.map((item) => localizeCommandDefinition(item, language)),
    })),
  })();
}
