import type { ProductLanguage } from '@contract/types';
import { pickByLocale } from '../i18n/messages.ts';

export interface SelectOption {
  value: number;
  label: string;
}

export const RMMV_NONE_LABEL = '无';
export const RMMV_BATTLE_SPAN_LABEL = '战斗';
const RMMV_DATABASE_SUMMARY_BY_LOCALE = {
  'zh-CN': {
    turnEnding: '回合结束',
    turn: '回合',
    enemy: '敌人',
    actor: '角色',
    switch: '开关',
    malformedCommand: '结构异常',
    parameterCount: '参数',
    malformedCommandList: '执行内容结构异常',
    emptyCommandList: '空执行内容',
    remainingPrefix: '还有',
    remainingSuffix: '条未显示',
    frameCount: '帧',
    maxCellsPerFrame: '单帧最多',
    cellCount: '个 cell',
  },
  'en-US': {
    turnEnding: 'Turn End',
    turn: 'Turn',
    enemy: 'Enemy',
    actor: 'Actor',
    switch: 'Switch',
    malformedCommand: 'Malformed command',
    parameterCount: 'parameters',
    malformedCommandList: 'Malformed command list',
    emptyCommandList: 'Empty command list',
    remainingPrefix: 'Plus',
    remainingSuffix: 'more hidden',
    frameCount: 'frames',
    maxCellsPerFrame: 'max',
    cellCount: 'cells per frame',
  },
} as const satisfies Record<ProductLanguage, Record<string, string>>;

export function databaseSummaryText(language: ProductLanguage): Record<string, string> {
  return pickByLocale<Record<string, string>>(language, RMMV_DATABASE_SUMMARY_BY_LOCALE);
}

export const GROUP_LABELS_BY_LOCALE = {
  'zh-CN': {
    Actors: '角色',
    Classes: '职业',
    Skills: '技能',
    Items: '物品',
    Weapons: '武器',
    Armors: '防具',
    Enemies: '敌人',
    Troops: '敌群',
    States: '状态',
    Animations: '动画',
    Tilesets: '图块组',
    CommonEvents: '公共事件',
    System: '系统',
    Types: '类型',
    Terms: '用语',
  },
  'en-US': {
    Actors: 'Actors',
    Classes: 'Classes',
    Skills: 'Skills',
    Items: 'Items',
    Weapons: 'Weapons',
    Armors: 'Armors',
    Enemies: 'Enemies',
    Troops: 'Troops',
    States: 'States',
    Animations: 'Animations',
    Tilesets: 'Tilesets',
    CommonEvents: 'Common Events',
    System: 'System',
    Types: 'Types',
    Terms: 'Terms',
  },
} as const satisfies Record<ProductLanguage, Record<string, string>>;

export const FIELD_LABELS_BY_LOCALE = {
  'zh-CN': {
  id: '编号',
  name: '名称',
  gameTitle: '游戏标题',
  versionId: '版本 ID',
  editMapId: '编辑地图',
  classId: '职业',
  initialLevel: '初始等级',
  maxLevel: '最高等级',
  nickname: '昵称',
  profile: '简介',
  description: '说明',
  note: '备注',
  characterName: '行走图',
  characterIndex: '行走图索引',
  faceName: '脸图',
  faceIndex: '脸图索引',
  battlerName: '战斗图',
  battlerHue: '战斗图色相',
  iconIndex: '图标编号',
  price: '价格',
  animationId: '动画',
  stypeId: '技能类型',
  itypeId: '物品类型',
  wtypeId: '武器类型',
  atypeId: '防具类型',
  etypeId: '装备类型',
  mpCost: 'MP 消耗',
  tpCost: 'TP 消耗',
  tpGain: '获得 TP',
  scope: '作用范围',
  occasion: '可用场景',
  speed: '速度修正',
  successRate: '成功率',
  repeats: '连续次数',
  hitType: '命中类型',
  requiredWtypeId1: '必要武器 1',
  requiredWtypeId2: '必要武器 2',
  consumable: '消耗品',
  exp: '经验值',
  gold: '金币',
  restriction: '行动限制',
  priority: '优先级',
  motion: '动作',
  overlay: '叠加显示',
  autoRemovalTiming: '自动解除',
  minTurns: '最少回合',
  maxTurns: '最多回合',
  removeAtBattleEnd: '战斗结束解除',
  removeByRestriction: '行动限制解除',
  removeByDamage: '受伤解除',
  chanceByDamage: '受伤解除概率',
  removeByWalking: '步行解除',
  stepsToRemove: '解除步数',
  message1: '提示 1',
  message2: '提示 2',
  message3: '提示 3',
  message4: '提示 4',
  animation1Name: '动画图像 1',
  animation1Hue: '图像 1 色相',
  animation2Name: '动画图像 2',
  animation2Hue: '图像 2 色相',
  position: '显示位置',
  mode: '模式',
  trigger: '触发方式',
  switchId: '条件开关',
  testTroopId: '测试敌群',
  startMapId: '起始地图',
  startX: '起始 X',
  startY: '起始 Y',
  title1Name: '标题图 1',
  title2Name: '标题图 2',
  battleback1Name: '战斗背景 1',
  battleback2Name: '战斗背景 2',
  currencyUnit: '货币单位',
  locale: '语言',
  optDisplayTp: '显示 TP',
  optDrawTitle: '绘制标题',
  optExtraExp: '替补获得经验',
  optFloorDeath: '地形伤害死亡',
  optFollowers: '显示队列成员',
  optSideView: '侧视战斗',
  optSlipDeath: '中毒死亡',
  optTransparent: '透明开始',
  switches: '开关',
  variables: '变量',
  elements: '属性',
  skillTypes: '技能类型',
  weaponTypes: '武器类型',
  armorTypes: '防具类型',
  equipTypes: '装备类型',
  partyMembers: '初始队伍',
  testBattlers: '测试战斗成员',
  boat: '小船',
  ship: '大船',
  airship: '飞空艇',
  titleBgm: '标题 BGM',
  battleBgm: '战斗 BGM',
  victoryMe: '胜利 ME',
  defeatMe: '战败 ME',
  gameoverMe: '游戏结束 ME',
  sounds: '系统音效',
  terms: '用语',
  menuCommands: '菜单命令',
  windowTone: '窗口色调',
  damage: '伤害',
  effects: '使用效果',
  traits: '特性',
  params: '能力值',
  equips: '初始装备',
  expParams: '经验曲线',
  learnings: '习得技能',
  actions: '行动模式',
  dropItems: '掉落物',
  members: '敌群成员',
  pages: '战斗事件页',
  frames: '动画帧',
  timings: '动画时机',
  tilesetNames: '图块图片',
  flags: '图块标志',
  list: '执行内容',
  basic: '基础用语',
  commands: '命令用语',
  messages: '消息用语',
  },
  'en-US': {
  id: 'ID',
  name: 'Name',
  gameTitle: 'Game Title',
  versionId: 'Version ID',
  editMapId: 'Edit Map',
  classId: 'Class',
  initialLevel: 'Initial Level',
  maxLevel: 'Max Level',
  nickname: 'Nickname',
  profile: 'Profile',
  description: 'Description',
  note: 'Note',
  characterName: 'Character Sprite',
  characterIndex: 'Character Sprite Index',
  faceName: 'Face Graphic',
  faceIndex: 'Face Index',
  battlerName: 'Battler Graphic',
  battlerHue: 'Battler Hue',
  iconIndex: 'Icon ID',
  price: 'Price',
  animationId: 'Animation',
  stypeId: 'Skill Type',
  itypeId: 'Item Type',
  wtypeId: 'Weapon Type',
  atypeId: 'Armor Type',
  etypeId: 'Equipment Type',
  mpCost: 'MP Cost',
  tpCost: 'TP Cost',
  tpGain: 'TP Gain',
  scope: 'Scope',
  occasion: 'Occasion',
  speed: 'Speed Modifier',
  successRate: 'Success Rate',
  repeats: 'Repeats',
  hitType: 'Hit Type',
  requiredWtypeId1: 'Required Weapon 1',
  requiredWtypeId2: 'Required Weapon 2',
  consumable: 'Consumable',
  exp: 'EXP',
  gold: 'Gold',
  restriction: 'Restriction',
  priority: 'Priority',
  motion: 'Motion',
  overlay: 'Overlay',
  autoRemovalTiming: 'Auto-removal Timing',
  minTurns: 'Min Turns',
  maxTurns: 'Max Turns',
  removeAtBattleEnd: 'Remove at Battle End',
  removeByRestriction: 'Remove by Restriction',
  removeByDamage: 'Remove by Damage',
  chanceByDamage: 'Damage Removal Chance',
  removeByWalking: 'Remove by Walking',
  stepsToRemove: 'Steps to Remove',
  message1: 'Message 1',
  message2: 'Message 2',
  message3: 'Message 3',
  message4: 'Message 4',
  animation1Name: 'Animation Image 1',
  animation1Hue: 'Image 1 Hue',
  animation2Name: 'Animation Image 2',
  animation2Hue: 'Image 2 Hue',
  position: 'Position',
  mode: 'Mode',
  trigger: 'Trigger',
  switchId: 'Condition Switch',
  testTroopId: 'Test Troop',
  startMapId: 'Start Map',
  startX: 'Start X',
  startY: 'Start Y',
  title1Name: 'Title Image 1',
  title2Name: 'Title Image 2',
  battleback1Name: 'Battleback 1',
  battleback2Name: 'Battleback 2',
  currencyUnit: 'Currency Unit',
  locale: 'Locale',
  optDisplayTp: 'Display TP',
  optDrawTitle: 'Draw Title',
  optExtraExp: 'Reserve Members Gain EXP',
  optFloorDeath: 'Floor Damage Death',
  optFollowers: 'Show Followers',
  optSideView: 'Side-view Battle',
  optSlipDeath: 'Slip Damage Death',
  optTransparent: 'Transparent Start',
  switches: 'Switches',
  variables: 'Variables',
  elements: 'Elements',
  skillTypes: 'Skill Types',
  weaponTypes: 'Weapon Types',
  armorTypes: 'Armor Types',
  equipTypes: 'Equipment Types',
  partyMembers: 'Initial Party',
  testBattlers: 'Test Battlers',
  boat: 'Boat',
  ship: 'Ship',
  airship: 'Airship',
  titleBgm: 'Title BGM',
  battleBgm: 'Battle BGM',
  victoryMe: 'Victory ME',
  defeatMe: 'Defeat ME',
  gameoverMe: 'Game Over ME',
  sounds: 'System Sounds',
  terms: 'Terms',
  menuCommands: 'Menu Commands',
  windowTone: 'Window Tone',
  damage: 'Damage',
  effects: 'Effects',
  traits: 'Traits',
  params: 'Parameters',
  equips: 'Initial Equipment',
  expParams: 'EXP Curve',
  learnings: 'Learned Skills',
  actions: 'Action Patterns',
  dropItems: 'Drops',
  members: 'Troop Members',
  pages: 'Battle Event Pages',
  frames: 'Animation Frames',
  timings: 'Animation Timings',
  tilesetNames: 'Tileset Images',
  flags: 'Tile Flags',
  list: 'Contents',
  basic: 'Basic Terms',
  commands: 'Command Terms',
  messages: 'Message Terms',
  },
} as const satisfies Record<ProductLanguage, Record<string, string>>;

export const PARAM_OPTIONS = [
  '最大 HP', '最大 MP', '攻击力', '防御力', '魔法力', '魔法防御', '敏捷', '幸运',
].map((label, value) => ({ value, label }));

export const XPARAM_OPTIONS = [
  '命中率', '闪避率', '会心率', '会心闪避', '魔法闪避', '魔法反射', '反击率', 'HP 再生', 'MP 再生', 'TP 再生',
].map((label, value) => ({ value, label }));

export const SPARAM_OPTIONS = [
  '被攻击率', '防御效果率', '恢复效果率', '药理知识', 'MP 消耗率', 'TP 充能率', '物理伤害率', '魔法伤害率', '地形伤害率', '经验获得率',
].map((label, value) => ({ value, label }));

export const TRAIT_CODES: SelectOption[] = [
  { value: 11, label: '属性有效度' },
  { value: 12, label: '弱化有效度' },
  { value: 13, label: '状态有效度' },
  { value: 14, label: '状态免疫' },
  { value: 21, label: '普通能力值' },
  { value: 22, label: '追加能力值' },
  { value: 23, label: '特殊能力值' },
  { value: 31, label: '攻击属性' },
  { value: 32, label: '攻击状态' },
  { value: 33, label: '攻击速度补正' },
  { value: 34, label: '攻击次数追加' },
  { value: 41, label: '添加技能类型' },
  { value: 42, label: '封印技能类型' },
  { value: 43, label: '添加技能' },
  { value: 44, label: '封印技能' },
  { value: 51, label: '装备武器类型' },
  { value: 52, label: '装备防具类型' },
  { value: 53, label: '固定装备' },
  { value: 54, label: '封印装备' },
  { value: 55, label: '装备槽类型' },
  { value: 61, label: '追加行动次数' },
  { value: 62, label: '特殊标志' },
  { value: 63, label: '消失效果' },
  { value: 64, label: '队伍能力' },
];

export const EFFECT_CODES: SelectOption[] = [
  { value: 11, label: '恢复 HP' },
  { value: 12, label: '恢复 MP' },
  { value: 13, label: '获得 TP' },
  { value: 21, label: '附加状态' },
  { value: 22, label: '解除状态' },
  { value: 31, label: '强化能力值' },
  { value: 32, label: '弱化能力值' },
  { value: 33, label: '解除强化' },
  { value: 34, label: '解除弱化' },
  { value: 41, label: '特殊效果' },
  { value: 42, label: '成长' },
  { value: 43, label: '习得技能' },
  { value: 44, label: '公共事件' },
];

export const ITEM_TYPE_OPTIONS: SelectOption[] = [
  { value: 1, label: '普通物品' },
  { value: 2, label: '关键物品' },
  { value: 3, label: '隐藏物品 A' },
  { value: 4, label: '隐藏物品 B' },
];

export const DROP_KIND_OPTIONS: SelectOption[] = [
  { value: 0, label: '无' },
  { value: 1, label: '物品' },
  { value: 2, label: '武器' },
  { value: 3, label: '防具' },
];

export const FLAG_BITS: SelectOption[] = [
  { value: 0x01, label: '下阻塞' },
  { value: 0x02, label: '左阻塞' },
  { value: 0x04, label: '右阻塞' },
  { value: 0x08, label: '上阻塞' },
  { value: 0x10, label: '星标' },
  { value: 0x20, label: '梯子' },
  { value: 0x40, label: '草丛' },
  { value: 0x80, label: '柜台' },
  { value: 0x100, label: '伤害地形' },
];

export const DAMAGE_TYPE_OPTIONS: SelectOption[] = [
  { value: 0, label: '无' },
  { value: 1, label: 'HP 伤害' },
  { value: 2, label: 'MP 伤害' },
  { value: 3, label: 'HP 恢复' },
  { value: 4, label: 'MP 恢复' },
  { value: 5, label: 'HP 吸收' },
  { value: 6, label: 'MP 吸收' },
];

export const SCOPE_OPTIONS: SelectOption[] = [
  { value: 0, label: '无' },
  { value: 1, label: '敌单体' },
  { value: 2, label: '敌全体' },
  { value: 3, label: '敌随机 1 次' },
  { value: 4, label: '敌随机 2 次' },
  { value: 5, label: '敌随机 3 次' },
  { value: 6, label: '敌随机 4 次' },
  { value: 7, label: '我方单体' },
  { value: 8, label: '我方全体' },
  { value: 9, label: '我方单体（战斗不能）' },
  { value: 10, label: '我方全体（战斗不能）' },
  { value: 11, label: '使用者' },
];

export const OCCASION_OPTIONS: SelectOption[] = [
  { value: 0, label: '总是' },
  { value: 1, label: '仅战斗' },
  { value: 2, label: '仅菜单' },
  { value: 3, label: '不可使用' },
];

export const HIT_TYPE_OPTIONS: SelectOption[] = [
  { value: 0, label: '必中' },
  { value: 1, label: '物理攻击' },
  { value: 2, label: '魔法攻击' },
];

export const TRIGGER_OPTIONS: SelectOption[] = [
  { value: 0, label: '无' },
  { value: 1, label: '自动执行' },
  { value: 2, label: '并行处理' },
];

export const STATE_RESTRICTION_OPTIONS: SelectOption[] = [
  { value: 0, label: '无' },
  { value: 1, label: '攻击敌人' },
  { value: 2, label: '攻击任意目标' },
  { value: 3, label: '攻击同伴' },
  { value: 4, label: '不能行动' },
];

export const STATE_AUTO_REMOVE_OPTIONS: SelectOption[] = [
  { value: 0, label: '无' },
  { value: 1, label: '行动结束' },
  { value: 2, label: '回合结束' },
];

export const STATE_MOTION_OPTIONS: SelectOption[] = [
  { value: 0, label: '普通' },
  { value: 1, label: '异常' },
  { value: 2, label: '睡眠' },
  { value: 3, label: '死亡' },
];

export const STATE_OVERLAY_OPTIONS: SelectOption[] = [
  { value: 0, label: '无' },
  { value: 1, label: '中毒' },
  { value: 2, label: '黑暗' },
  { value: 3, label: '沉默' },
  { value: 4, label: '愤怒' },
  { value: 5, label: '混乱' },
  { value: 6, label: '魅惑' },
  { value: 7, label: '睡眠' },
  { value: 8, label: '麻痹' },
  { value: 9, label: '诅咒' },
  { value: 10, label: '恐惧' },
];

export const ANIMATION_POSITION_OPTIONS: SelectOption[] = [
  { value: 0, label: '头部' },
  { value: 1, label: '中央' },
  { value: 2, label: '脚下' },
  { value: 3, label: '画面' },
];

export const TILESET_MODE_OPTIONS: SelectOption[] = [
  { value: 0, label: 'VX Ace 兼容' },
  { value: 1, label: 'MV 标准' },
];

export const TILESET_NAME_LABELS = ['A1', 'A2', 'A3', 'A4', 'A5', 'B', 'C', 'D', 'E'];
export const MENU_COMMAND_LABELS = ['物品', '技能', '装备', '状态', '整队', '保存'];
export const TONE_LABELS = ['红', '绿', '蓝', '灰'];
export const SOUND_LABELS = [
  '光标', '确定', '取消', '蜂鸣', '装备', '保存', '读取', '战斗开始',
  '逃跑', '敌人攻击', '敌人受伤', '敌人消失', 'Boss 消失 1', 'Boss 消失 2',
  '角色受伤', '角色倒下', '恢复', '未命中', '闪避', '魔法闪避',
  '魔法反射', '商店', '使用物品', '使用技能',
];
export const TERM_LABELS: Record<string, string[]> = {
  basic: ['等级', '等级缩写', 'HP', 'HP 缩写', 'MP', 'MP 缩写', 'TP', 'TP 缩写', '经验值', '经验值缩写'],
  params: ['最大 HP', '最大 MP', '攻击', '防御', '魔法攻击', '魔法防御', '敏捷', '幸运', '命中', '回避'],
  commands: [
    '战斗', '逃跑', '攻击', '防御', '物品', '技能', '装备', '状态', '整队', '保存', '游戏结束', '选项',
    '武器', '防具', '贵重物品', '装备', '最强装备', '全部卸下', '新的游戏', '继续', '标题画面', '取消', '购买', '卖出',
  ],
};

const DATABASE_TEXT_BY_SOURCE_LABEL_BY_LOCALE: Record<ProductLanguage, Record<string, string>> = {
  'zh-CN': {},
  'en-US': {
  无: 'None',
  普通物品: 'Regular Item',
  关键物品: 'Key Item',
  '隐藏物品 A': 'Hidden Item A',
  '隐藏物品 B': 'Hidden Item B',
  物品: 'Item',
  武器: 'Weapon',
  防具: 'Armor',
  下阻塞: 'Passage Down Blocked',
  左阻塞: 'Passage Left Blocked',
  右阻塞: 'Passage Right Blocked',
  上阻塞: 'Passage Up Blocked',
  星标: 'Star',
  梯子: 'Ladder',
  草丛: 'Bush',
  柜台: 'Counter',
  伤害地形: 'Damage Floor',
  'HP 伤害': 'HP Damage',
  'MP 伤害': 'MP Damage',
  'HP 恢复': 'HP Recovery',
  'MP 恢复': 'MP Recovery',
  'HP 吸收': 'HP Drain',
  'MP 吸收': 'MP Drain',
  敌单体: 'One Enemy',
  敌全体: 'All Enemies',
  '敌随机 1 次': '1 Random Enemy',
  '敌随机 2 次': '2 Random Enemies',
  '敌随机 3 次': '3 Random Enemies',
  '敌随机 4 次': '4 Random Enemies',
  我方单体: 'One Ally',
  我方全体: 'All Allies',
  '我方单体（战斗不能）': 'One Fallen Ally',
  '我方全体（战斗不能）': 'All Fallen Allies',
  使用者: 'The User',
  总是: 'Always',
  仅战斗: 'Battle Screen',
  仅菜单: 'Menu Screen',
  不可使用: 'Never',
  必中: 'Certain Hit',
  物理攻击: 'Physical Attack',
  魔法攻击: 'Magical Attack',
  自动执行: 'Autorun',
  并行处理: 'Parallel',
  攻击敌人: 'Attack an Enemy',
  攻击任意目标: 'Attack Anyone',
  攻击同伴: 'Attack an Ally',
  不能行动: 'Cannot Move',
  行动结束: 'Action End',
  回合结束: 'Turn End',
  普通: 'Normal',
  异常: 'Abnormal',
  睡眠: 'Sleep',
  死亡: 'Dead',
  头部: 'Head',
  中央: 'Center',
  脚下: 'Feet',
  画面: 'Screen',
  'VX Ace 兼容': 'VX Ace Compatible',
  'MV 标准': 'MV Standard',
  '最大 HP': 'Max HP',
  '最大 MP': 'Max MP',
  攻击力: 'Attack',
  防御力: 'Defense',
  魔法力: 'Magic Attack',
  魔法防御: 'Magic Defense',
  敏捷: 'Agility',
  幸运: 'Luck',
  命中率: 'Hit Rate',
  闪避率: 'Evasion Rate',
  会心率: 'Critical Rate',
  会心闪避: 'Critical Evasion',
  魔法闪避: 'Magic Evasion',
  魔法反射: 'Magic Reflection',
  反击率: 'Counter Rate',
  'HP 再生': 'HP Regeneration',
  'MP 再生': 'MP Regeneration',
  'TP 再生': 'TP Regeneration',
  被攻击率: 'Target Rate',
  防御效果率: 'Guard Effect',
  恢复效果率: 'Recovery Effect',
  药理知识: 'Pharmacology',
  'MP 消耗率': 'MP Cost Rate',
  'TP 充能率': 'TP Charge Rate',
  物理伤害率: 'Physical Damage Rate',
  魔法伤害率: 'Magical Damage Rate',
  地形伤害率: 'Floor Damage Rate',
  经验获得率: 'EXP Rate',
  属性有效度: 'Element Rate',
  弱化有效度: 'Debuff Rate',
  状态有效度: 'State Rate',
  状态免疫: 'State Resist',
  普通能力值: 'Parameter',
  追加能力值: 'Extra Parameter',
  特殊能力值: 'Special Parameter',
  攻击属性: 'Attack Element',
  攻击状态: 'Attack State',
  攻击速度补正: 'Attack Speed',
  攻击次数追加: 'Attack Times',
  添加技能类型: 'Add Skill Type',
  封印技能类型: 'Seal Skill Type',
  添加技能: 'Add Skill',
  封印技能: 'Seal Skill',
  装备武器类型: 'Equip Weapon Type',
  装备防具类型: 'Equip Armor Type',
  固定装备: 'Lock Equip',
  封印装备: 'Seal Equip',
  装备槽类型: 'Slot Type',
  追加行动次数: 'Action Times',
  特殊标志: 'Special Flag',
  消失效果: 'Collapse Effect',
  队伍能力: 'Party Ability',
  '恢复 HP': 'Recover HP',
  '恢复 MP': 'Recover MP',
  '获得 TP': 'Gain TP',
  附加状态: 'Add State',
  解除状态: 'Remove State',
  强化能力值: 'Add Buff',
  弱化能力值: 'Add Debuff',
  解除强化: 'Remove Buff',
  解除弱化: 'Remove Debuff',
  特殊效果: 'Special Effect',
  成长: 'Grow',
  习得技能: 'Learn Skill',
  公共事件: 'Common Event',
  光标: 'Cursor',
  确定: 'OK',
  取消: 'Cancel',
  蜂鸣: 'Buzzer',
  装备: 'Equip',
  保存: 'Save',
  读取: 'Load',
  战斗开始: 'Battle Start',
  逃跑: 'Escape',
  敌人攻击: 'Enemy Attack',
  敌人受伤: 'Enemy Damage',
  敌人消失: 'Enemy Collapse',
  'Boss 消失 1': 'Boss Collapse 1',
  'Boss 消失 2': 'Boss Collapse 2',
  角色受伤: 'Actor Damage',
  角色倒下: 'Actor Collapse',
  恢复: 'Recovery',
  未命中: 'Miss',
  闪避: 'Evasion',
  商店: 'Shop',
  使用物品: 'Use Item',
  使用技能: 'Use Skill',
  红: 'Red',
  绿: 'Green',
  蓝: 'Blue',
  灰: 'Gray',
  等级: 'Level',
  等级缩写: 'Level Abbreviation',
  'HP 缩写': 'HP Abbreviation',
  'MP 缩写': 'MP Abbreviation',
  'TP 缩写': 'TP Abbreviation',
  经验值: 'EXP',
  经验值缩写: 'EXP Abbreviation',
  攻击: 'Attack',
  防御: 'Guard',
  命中: 'Hit',
  回避: 'Evasion',
  战斗: 'Fight',
  技能: 'Skill',
  状态: 'Status',
  整队: 'Formation',
  游戏结束: 'Game End',
  选项: 'Options',
  贵重物品: 'Key Items',
  最强装备: 'Optimize',
  全部卸下: 'Clear',
  新的游戏: 'New Game',
  继续: 'Continue',
  标题画面: 'Title Screen',
  购买: 'Buy',
  卖出: 'Sell',
  图案: 'Pattern',
  缩放: 'Scale',
  旋转: 'Rotation',
  镜像: 'Mirror',
  不透明度: 'Opacity',
  合成: 'Blend',
  回合: 'Turn',
  瞬间: 'Moment',
  目标: 'Target',
  隐藏目标: 'Hide Target',
  中毒: 'Poison',
  黑暗: 'Blind',
  沉默: 'Silence',
  愤怒: 'Rage',
  混乱: 'Confusion',
  魅惑: 'Fascination',
  麻痹: 'Paralysis',
  诅咒: 'Curse',
  恐惧: 'Fear',
  加算: 'Additive',
  正片叠底: 'Multiply',
  滤色: 'Screen',
  },
} as const satisfies Record<ProductLanguage, Record<string, string>>;

export const MV_TERMS_MESSAGE_LABELS: Record<string, string> = {
  actionFailure: '无效果',
  actorDamage: '我方受伤',
  actorDrain: '我方被吸收',
  actorGain: '我方获得',
  actorLoss: '我方失去',
  actorNoDamage: '我方无伤',
  actorNoHit: '我方未命中',
  actorRecovery: '我方恢复',
  alwaysDash: '始终奔跑',
  bgmVolume: 'BGM 音量',
  bgsVolume: 'BGS 音量',
  buffAdd: '强化',
  buffRemove: '强化解除',
  commandRemember: '记忆指令',
  counterAttack: '反击',
  criticalToActor: '我方会心',
  criticalToEnemy: '敌方会心',
  debuffAdd: '弱化',
  defeat: '战败',
  enemyDamage: '敌方受伤',
  enemyDrain: '敌方被吸收',
  enemyGain: '敌方获得',
  enemyLoss: '敌方失去',
  enemyNoDamage: '敌方无伤',
  enemyNoHit: '敌方未命中',
  enemyRecovery: '敌方恢复',
  escapeFailure: '逃跑失败',
  escapeStart: '逃跑开始',
  evasion: '物理闪避',
  expNext: '下级经验',
  expTotal: '当前经验',
  file: '存档文件',
  levelUp: '升级',
  loadMessage: '读取提示',
  magicEvasion: '魔法闪避',
  magicReflection: '魔法反射',
  meVolume: 'ME 音量',
  obtainExp: '获得经验',
  obtainGold: '获得金币',
  obtainItem: '获得物品',
  obtainSkill: '习得技能',
  partyName: '队伍名',
  possession: '持有数',
  preemptive: '先制',
  saveMessage: '保存提示',
  seVolume: 'SE 音量',
  substitute: '保护',
  surprise: '偷袭',
  useItem: '使用物品',
  victory: '胜利',
};

export const MV_TERMS_MESSAGE_LABELS_BY_LOCALE = {
  'zh-CN': MV_TERMS_MESSAGE_LABELS,
  'en-US': {
    actionFailure: 'No Effect',
    actorDamage: 'Actor Damage',
    actorDrain: 'Actor Drain',
    actorGain: 'Actor Gain',
    actorLoss: 'Actor Loss',
    actorNoDamage: 'Actor No Damage',
    actorNoHit: 'Actor Missed',
    actorRecovery: 'Actor Recovery',
    alwaysDash: 'Always Dash',
    bgmVolume: 'BGM Volume',
    bgsVolume: 'BGS Volume',
    buffAdd: 'Buff Add',
    buffRemove: 'Buff Remove',
    commandRemember: 'Command Remember',
    counterAttack: 'Counterattack',
    criticalToActor: 'Actor Critical',
    criticalToEnemy: 'Enemy Critical',
    debuffAdd: 'Debuff Add',
    defeat: 'Defeat',
    enemyDamage: 'Enemy Damage',
    enemyDrain: 'Enemy Drain',
    enemyGain: 'Enemy Gain',
    enemyLoss: 'Enemy Loss',
    enemyNoDamage: 'Enemy No Damage',
    enemyNoHit: 'Enemy Missed',
    enemyRecovery: 'Enemy Recovery',
    escapeFailure: 'Escape Failure',
    escapeStart: 'Escape Start',
    evasion: 'Physical Evasion',
    expNext: 'Next Level EXP',
    expTotal: 'Current EXP',
    file: 'Save File',
    levelUp: 'Level Up',
    loadMessage: 'Load Message',
    magicEvasion: 'Magic Evasion',
    magicReflection: 'Magic Reflection',
    meVolume: 'ME Volume',
    obtainExp: 'Obtain EXP',
    obtainGold: 'Obtain Gold',
    obtainItem: 'Obtain Item',
    obtainSkill: 'Obtain Skill',
    partyName: 'Party Name',
    possession: 'Possession',
    preemptive: 'Preemptive',
    saveMessage: 'Save Message',
    seVolume: 'SE Volume',
    substitute: 'Substitute',
    surprise: 'Surprise',
    useItem: 'Use Item',
    victory: 'Victory',
  },
} as const satisfies Record<ProductLanguage, Record<string, string>>;

export function databaseGroupLabel(key: string, language: ProductLanguage): string {
  return pickByLocale<Record<string, string>>(language, GROUP_LABELS_BY_LOCALE)[key] || key;
}

export function databaseFieldLabel(key: string, language: ProductLanguage): string {
  return pickByLocale<Record<string, string>>(language, FIELD_LABELS_BY_LOCALE)[key] || key;
}

export function localizeDatabaseLabel(label: string, language: ProductLanguage): string {
  return pickByLocale(language, {
    'zh-CN': () => label,
    'en-US': () => DATABASE_TEXT_BY_SOURCE_LABEL_BY_LOCALE['en-US'][label] || label,
  })();
}

export function localizeDatabaseOptions(options: ReadonlyArray<SelectOption>, language: ProductLanguage): SelectOption[] {
  return pickByLocale<() => SelectOption[]>(language, {
    'zh-CN': () => options.map((option) => ({ ...option })),
    'en-US': () => options.map((option) => ({ ...option, label: localizeDatabaseLabel(option.label, language) })),
  })();
}

export function databaseTermMessageLabel(key: string, language: ProductLanguage): string {
  return pickByLocale<Record<string, string>>(language, MV_TERMS_MESSAGE_LABELS_BY_LOCALE)[key] || key;
}

export const MV_CLASS_PARAM_LEVELS = Array.from({ length: 99 }, (_entry, index) => index + 1);
export const MV_CLASS_PARAM_COUNT = 8;
export const MV_CLASS_PARAM_ROW_LENGTH = 100;

export const MV_ANIMATION_CELL_FIELDS = [
  { key: 'pattern', label: '图案' },
  { key: 'x', label: 'X' },
  { key: 'y', label: 'Y' },
  { key: 'scale', label: '缩放' },
  { key: 'rotation', label: '旋转' },
  { key: 'mirror', label: '镜像' },
  { key: 'opacity', label: '不透明度' },
  { key: 'blendMode', label: '合成' },
] as const;

export const MV_TROOP_PAGE_SPANS = [
  { value: 0, label: '战斗' },
  { value: 1, label: '回合' },
  { value: 2, label: '瞬间' },
] as const;

export const MV_ANIMATION_FLASH_SCOPES = [
  { value: 0, label: '无' },
  { value: 1, label: '目标' },
  { value: 2, label: '画面' },
  { value: 3, label: '隐藏目标' },
] as const;

export const MV_ANIMATION_BLEND_MODES = [
  { value: 0, label: '普通' },
  { value: 1, label: '加算' },
  { value: 2, label: '正片叠底' },
  { value: 3, label: '滤色' },
] as const;
