import type { RpgMakerEngine } from '../../../../contract/types.ts';

export const UNLIMITED_TILE_LAYERS_PLUGIN_NAME = 'RPGAgentUnlimitedTileLayers';
export const UNLIMITED_TILE_LAYERS_PLUGIN_VERSION = '1.0.0';

const COMMON_RUNTIME = String.raw`
  'use strict';
  var TAG = 'tileLayers';
  var BLOCK_PATTERN = /<tileLayers>([\s\S]*?)<\/tileLayers>/gi;

  function parseLayers(note) {
    var layers = [];
    var source = String(note || '');
    var match;
    BLOCK_PATTERN.lastIndex = 0;
    while ((match = BLOCK_PATTERN.exec(source))) {
      var parsed;
      try { parsed = JSON.parse(match[1]); } catch (error) { continue; }
      var items = Array.isArray(parsed) ? parsed : [parsed];
      for (var i = 0; i < items.length; i++) {
        var item = items[i];
        if (item && typeof item === 'object' && Array.isArray(item.tiles)) layers.push(item.tiles);
      }
    }
    return layers;
  }

  function syntheticData(tiles, width, height) {
    var size = width * height;
    var data = new Array(size * 6);
    for (var i = 0; i < size; i++) data[i] = tiles[i] || 0;
    for (var z = size; z < data.length; z++) data[z] = 0;
    return data;
  }

  function tilesetBitmaps() {
    var tileset = $gameMap && $gameMap.tileset ? $gameMap.tileset() : null;
    var names = tileset && Array.isArray(tileset.tilesetNames) ? tileset.tilesetNames : [];
    var bitmaps = [];
    for (var i = 0; i < names.length; i++) bitmaps.push(ImageManager.loadTileset(names[i]));
    return bitmaps;
  }

  function assignBitmaps(tilemap, bitmaps) {
    if (typeof tilemap.setBitmaps === 'function') tilemap.setBitmaps(bitmaps);
    else tilemap.bitmaps = bitmaps;
  }

  function createExtraTilemaps(spriteset) {
    spriteset._rpgAgentExtraTilemaps = [];
    if (typeof $dataMap === 'undefined' || !$dataMap) return;
    var layers = parseLayers($dataMap.note);
    if (!layers.length) return;
    var width = $gameMap.width();
    var height = $gameMap.height();
    for (var i = 0; i < layers.length; i++) {
      if (!layers[i].some(function(tileId) { return tileId > 0; })) continue;
      var tilemap = new Tilemap();
      tilemap.tileWidth = $gameMap.tileWidth();
      tilemap.tileHeight = $gameMap.tileHeight();
      tilemap.setData(width, height, syntheticData(layers[i], width, height));
      tilemap.horizontalWrap = false;
      tilemap.verticalWrap = false;
      var bitmaps = tilesetBitmaps();
      assignBitmaps(tilemap, bitmaps);
      tilemap.flags = $gameMap.tilesetFlags();
      for (var b = 0; b < bitmaps.length; b++) {
        (function(target, bitmap) {
          if (bitmap && !bitmap.isReady()) bitmap.addLoadListener(function() { target.refresh(); });
        })(tilemap, bitmaps[b]);
      }
      spriteset._baseSprite.addChild(tilemap);
      spriteset._rpgAgentExtraTilemaps.push(tilemap);
      tilemap.refresh();
    }
  }

  var originalCreateTilemap = Spriteset_Map.prototype.createTilemap;
  Spriteset_Map.prototype.createTilemap = function() {
    originalCreateTilemap.call(this);
    createExtraTilemaps(this);
  };

  var originalUpdateTilemap = Spriteset_Map.prototype.updateTilemap;
  Spriteset_Map.prototype.updateTilemap = function() {
    originalUpdateTilemap.call(this);
    var extras = this._rpgAgentExtraTilemaps || [];
    for (var i = 0; i < extras.length; i++) {
      extras[i].origin.x = this._tilemap.origin.x;
      extras[i].origin.y = this._tilemap.origin.y;
    }
  };
`;

export function buildUnlimitedTileLayersRuntimePlugin(engine: RpgMakerEngine): string {
  const target = engine === 'rpg-maker-mz' ? 'MZ' : 'MV';
  return `/*:\n * @target ${target}\n * @plugindesc RPG Agent Unlimited Tile Layers ${UNLIMITED_TILE_LAYERS_PLUGIN_VERSION}\n * @author RPG Agent\n * @help\n * Managed by RPG Agent. Do not edit this file directly.\n * Renders extra tile layers stored in the map note <${'tileLayers'}> blocks.\n * Protocol version: ${UNLIMITED_TILE_LAYERS_PLUGIN_VERSION}\n */\n\n(function() {\n${COMMON_RUNTIME}})();\n`;
}
