import type { ProductLanguage } from '../../../contract/i18n.ts';
import { DEFAULT_PRODUCT_LANGUAGE, normalizeProductLanguage } from '../../../contract/i18n.ts';

const messages = {
  'zh-CN': {
    'staging.checkFailed': '检查暂存失败',
    'staging.savePrompt': '是否保存修改',
    'staging.save': '是',
    'staging.discard': '否',
    'staging.cancel': '取消',
    'staging.closeDetail': '当前项目存在暂存修改。选择“是”保存到工程；选择“否”放弃暂存；选择“取消”回到当前界面。',
    'staging.agentOperations': '将同时应用以下 Agent 数据库操作：\n{{operations}}',
    'staging.saveFailed': '保存修改失败',
    'staging.discardFailed': '放弃修改失败',
    'projects.selectDirectoryTitle': '选择 RPG Maker MV 或 MZ 项目目录',
    'projects.selectDirectoryUnsupported': '当前运行环境不支持选择项目目录',
    'projects.compatibilityWarningTitle': '工程兼容性提示',
    'projects.compatibilityWarningMessage': '这个 RPG Maker MZ 工程可以加载，但部分能力可能受限。',
    'projects.compatibilityVersionDetail': '核心版本为 {{detectedVersion}}，完整验证基线为 {{supportedVersion}}。写入结果可能与对应编辑器的预期不一致。',
    'projects.compatibilityEncryptionDetail': '工程使用了加密资源（{{scope}}）。地图、事件和数据库数据仍可编辑，但加密素材的列表、预览、替换和资源校验可能不完整。',
    'projects.compatibilityEncryptedImages': '图片',
    'projects.compatibilityEncryptedAudio': '音频',
    'projects.compatibilityEncryptedImagesAudio': '图片和音频',
    'projects.compatibilityImportDetail': '可以继续导入。建议先备份工程，并在对应版本的 RPG Maker 中检查最终结果。',
    'projects.compatibilityWriteDetail': '本次操作将把暂存修改写入版本未完整验证的 MZ 工程。请确认已备份工程。',
    'projects.compatibilityContinueImport': '仍然导入',
    'projects.compatibilityContinueWrite': '仍然写入',
    'projects.compatibilityCancel': '取消',
    'projects.compatibilitySuppress': '以后不再提示工程兼容性警告',
    'plugins.selectFileTitle': '选择 RPG Maker 插件',
    'plugins.selectFileUnsupported': '当前运行环境不支持选择插件文件',
    'assets.selectFileTitle': '选择 {{category}} 素材',
    'assets.selectFileUnsupported': '当前运行环境不支持选择素材文件',
    'settings.defaultVariant': '默认',
    'workflow.proposalMissing': '工作流提议不存在',
    'workflow.approveFailed': '无法批准工作流提议',
    'main.closeCheckFailed': '退出检查失败',
    'main.startupFailedTitle': '应用启动失败，即将退出',
    'main.startupFailedDetail': 'Agent Console 未能就绪：\n\n{{message}}\n\n常见原因：依赖加载失败或配置错误。',
    'updater.ok': '确定',
    'updater.updateNow': '立即更新',
    'updater.later': '稍后',
    'updater.restartNow': '立即重启',
    'updater.updateAvailableTitle': '发现新版本',
    'updater.updateAvailableMessage': '新版本 {{version}} 可用。',
    'updater.updateAvailableDetail': '将从 GitHub Releases 下载经过签名的更新。下载完成后会再次询问是否重启。',
    'updater.downloadedTitle': '更新已就绪',
    'updater.downloadedMessage': '版本 {{version}} 已下载完成。',
    'updater.downloadedDetail': '应用将重启以完成安装。',
    'updater.downloadFailedTitle': '更新下载失败',
    'updater.downloadFailedMessage': '无法下载经过签名的 GitHub 更新。',
    'updater.upToDateTitle': '已是最新版本',
    'updater.upToDateMessage': '当前版本为 {{version}}，没有可用更新。',
    'updater.notPackagedTitle': '无法检查更新',
    'updater.notPackagedMessage': '仅安装版（NSIS）支持应用内更新。开发模式请使用源码运行。',
    'updater.untrustedBuildTitle': '已阻止不安全的更新',
    'updater.untrustedBuildMessage': '当前安装版缺少可信发布者信息，或更新仓库配置不正确。请从官方 GitHub Release 重新安装。',
    'updater.checkFailedTitle': '检查更新失败',
    'updater.checkFailedMessage': '无法从 GitHub Releases 获取版本信息。请稍后重试或检查网络。',
  },
  'en-US': {
    'staging.checkFailed': 'Failed to Check Staging',
    'staging.savePrompt': 'Save Changes?',
    'staging.save': 'Save',
    'staging.discard': 'Discard',
    'staging.cancel': 'Cancel',
    'staging.closeDetail': 'The current project has staged changes. Save writes them to the project, Discard removes the staging draft, and Cancel returns to the current window.',
    'staging.agentOperations': 'The following Agent database operations will also be applied:\n{{operations}}',
    'staging.saveFailed': 'Failed to Save Changes',
    'staging.discardFailed': 'Failed to Discard Changes',
    'projects.selectDirectoryTitle': 'Select RPG Maker MV or MZ Project Folder',
    'projects.selectDirectoryUnsupported': 'This runtime does not support selecting a project folder.',
    'projects.compatibilityWarningTitle': 'Project Compatibility Notice',
    'projects.compatibilityWarningMessage': 'This RPG Maker MZ project can be loaded, but some capabilities may be limited.',
    'projects.compatibilityVersionDetail': 'The core version is {{detectedVersion}}; the fully validated baseline is {{supportedVersion}}. Writes may not behave as the matching editor expects.',
    'projects.compatibilityEncryptionDetail': 'The project uses encrypted {{scope}} resources. Map, event, and database data remain editable, but encrypted asset listing, preview, replacement, and validation may be incomplete.',
    'projects.compatibilityEncryptedImages': 'image',
    'projects.compatibilityEncryptedAudio': 'audio',
    'projects.compatibilityEncryptedImagesAudio': 'image and audio',
    'projects.compatibilityImportDetail': 'You can continue importing. Back up the project first and inspect the final result in the matching RPG Maker editor.',
    'projects.compatibilityWriteDetail': 'This operation will write staged changes to an MZ project whose version has not been fully validated. Confirm that the project is backed up.',
    'projects.compatibilityContinueImport': 'Import Anyway',
    'projects.compatibilityContinueWrite': 'Write Anyway',
    'projects.compatibilityCancel': 'Cancel',
    'projects.compatibilitySuppress': 'Do not show project compatibility warnings again',
    'plugins.selectFileTitle': 'Select RPG Maker Plugin',
    'plugins.selectFileUnsupported': 'This runtime does not support selecting a plugin file.',
    'assets.selectFileTitle': 'Select {{category}} Asset',
    'assets.selectFileUnsupported': 'This runtime does not support selecting an asset file.',
    'settings.defaultVariant': 'Default',
    'workflow.proposalMissing': 'Workflow proposal does not exist.',
    'workflow.approveFailed': 'Could not approve the workflow proposal.',
    'main.closeCheckFailed': 'Failed to Check Before Exit',
    'main.startupFailedTitle': 'Startup Failed',
    'main.startupFailedDetail': 'Agent Console could not finish startup:\n\n{{message}}\n\nCommon causes: dependency loading failed or configuration is invalid.',
    'updater.ok': 'OK',
    'updater.updateNow': 'Update Now',
    'updater.later': 'Later',
    'updater.restartNow': 'Restart Now',
    'updater.updateAvailableTitle': 'Update Available',
    'updater.updateAvailableMessage': 'Version {{version}} is available.',
    'updater.updateAvailableDetail': 'The signed update will be downloaded from GitHub Releases. You will be asked again before restarting.',
    'updater.downloadedTitle': 'Update Ready',
    'updater.downloadedMessage': 'Version {{version}} has finished downloading.',
    'updater.downloadedDetail': 'The app will restart to finish installing.',
    'updater.downloadFailedTitle': 'Update Download Failed',
    'updater.downloadFailedMessage': 'The signed GitHub update could not be downloaded.',
    'updater.upToDateTitle': 'Up to Date',
    'updater.upToDateMessage': 'You are on version {{version}}. No updates are available.',
    'updater.notPackagedTitle': 'Cannot Check for Updates',
    'updater.notPackagedMessage': 'In-app updates are available only in the NSIS installed build. Use source mode for development.',
    'updater.untrustedBuildTitle': 'Unsafe Update Blocked',
    'updater.untrustedBuildMessage': 'This installed build has no trusted publisher information or points at an unexpected update repository. Reinstall from the official GitHub Release.',
    'updater.checkFailedTitle': 'Update Check Failed',
    'updater.checkFailedMessage': 'Could not reach GitHub Releases. Try again later or check your network.',
  },
} as const;

export type ElectronMessageKey = keyof typeof messages['zh-CN'];

export function electronText(
  language: ProductLanguage | null | undefined,
  key: ElectronMessageKey,
  params: Record<string, string | number> = {},
): string {
  const normalized = normalizeProductLanguage(language);
  let text: string = messages[normalized][key] || messages[DEFAULT_PRODUCT_LANGUAGE][key] || key;
  for (const [name, value] of Object.entries(params)) {
    text = text.replaceAll(`{{${name}}}`, String(value));
  }
  return text;
}

export function stagingCloseButtons(language: ProductLanguage | null | undefined): string[] {
  return [
    electronText(language, 'staging.save'),
    electronText(language, 'staging.discard'),
    electronText(language, 'staging.cancel'),
  ];
}
