import assert from 'node:assert/strict';
import test from 'node:test';

import {
  filterMapPreviewPluginsJs,
  isMapPreviewPluginsJsPath,
} from './map-preview-plugins-filter.ts';

const SAMPLE = `// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CommunityBasic","status":true,"description":"Basic plugin.","parameters":{"cacheLimit":"20"}},
{"name":"MadeWithMv","status":false,"description":"Show splash [MV]","parameters":{}},
{"name":"CustomBattle","status":true,"description":"战斗增强","parameters":{"rate":"1.5"}}
];
`;

test('isMapPreviewPluginsJsPath matches js/plugins.js with and without www prefix', () => {
  assert.equal(isMapPreviewPluginsJsPath('js/plugins.js'), true);
  assert.equal(isMapPreviewPluginsJsPath('www/js/plugins.js'), true);
  assert.equal(isMapPreviewPluginsJsPath('/JS/Plugins.JS'), true);
  assert.equal(isMapPreviewPluginsJsPath('js\\plugins.js'), true);
  assert.equal(isMapPreviewPluginsJsPath('js/plugins/extra.js'), false);
  assert.equal(isMapPreviewPluginsJsPath('index.html'), false);
});

test('filter flips status only for the disabled names', () => {
  const filtered = filterMapPreviewPluginsJs(SAMPLE, ['CustomBattle']);
  assert.ok(filtered);
  const list = JSON.parse(filtered.slice(filtered.indexOf('['), filtered.lastIndexOf(']') + 1)) as Array<{
    name: string;
    status: boolean;
    parameters: Record<string, string>;
  }>;
  assert.deepEqual(list.map((entry) => [entry.name, entry.status]), [
    ['CommunityBasic', true],
    ['MadeWithMv', false],
    ['CustomBattle', false],
  ]);
  // Parameters and surrounding source stay intact.
  assert.equal(list[2]!.parameters.rate, '1.5');
  assert.ok(filtered.startsWith('// Generated by RPG Maker.'));
  assert.ok(filtered.trimEnd().endsWith('];'));
});

test('filter returns null when nothing changes', () => {
  assert.equal(filterMapPreviewPluginsJs(SAMPLE, []), null);
  assert.equal(filterMapPreviewPluginsJs(SAMPLE, ['UnknownPlugin']), null);
  // Already disabled entries need no rewrite.
  assert.equal(filterMapPreviewPluginsJs(SAMPLE, ['MadeWithMv']), null);
});

test('filter refuses to touch unparseable sources', () => {
  assert.equal(filterMapPreviewPluginsJs('var $plugins = [oops];', ['X']), null);
  assert.equal(filterMapPreviewPluginsJs('no array here', ['X']), null);
});
